### ISSUE TITLE
i don't want add any default parameters to restclient 

### ISSUE THREAD

**Issue by levonyang** [restsharp/RestSharp#1017]
restclient will add "Accept" parameter automatically before excute, I do not need this parameter.

I using RemoveDefaultParamter to delete it. but it only empty the value. this item will still be there.

How can i remove it?

**Comment by alexeyzimarev** [comment]
Accept parameter is set if you do not have it set manually. The values of accepted content types are set based on registered serialisers. This allows the service to send proper response. Since this is a standard parameter, I am wondering what problem are you having exactly? You service does not understand Accept? I can hardly believe it. Are you trying to save some network traffic?

**Comment by Prusilone** [comment]
Hi all,

It's strange of course, but I'm having the same problem: I'm calling a REST API from VB.NET using the RestSharp NuGet.
This API don't need any parameters except the auth-header: see the code here

```
 Dim Client As RestSharp.RestClient = GetClientREST(MyURL)
 Client.Authenticator = New RestSharp.Authenticators.HttpBasicAuthenticator(Username, Password)
 Dim Request = New RestSharp.RestRequest(Method.GET)
 Dim Response = wClient.Execute(wRequest)
```
Debugging this code I noticed:
- 0 params in Request before the Execute
- 2 params in Request after the Execute (Authorization / Accept)
seems that the "Accept" parameter is added during the Execute call...
In this case, my Response is [ HTTP 406 - NOT ACCEPTED ]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

Via browser and SOAPUI works fine; of course: no Accept param is added.

I also sniffed with WireShark my own HTTP traffic in order to match and see the differences beetwen the calls via browser, SOAPUI and VB.NET...and it's unfortunately the Accept parameter:
`Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml\r\n`

May you help me?

**Comment by Prusilone** [comment]
Sorry: I forgot this one: in the previous code I mentioned a GetClientREST(URL):

It's just an "esthetic mehtod"; in fact it's nothing more than a "new"...
```
Friend Function GetClientREST(URL As String) As RestSharp.RestClient
	If String.IsNullOrEmpty(URL) Then Throw New ArgumentNullException("URL", "URL parameter is not defined") 
    If Not System.Uri.TryCreate(URL, UriKind.Absolute, Nothing) Then 
		Throw New InvalidOperationException(String.Format("URL {0} not valid", URL))
	End if
    Return New RestSharp.RestClient(URL)
End Function
```

**Comment by Prusilone** [comment]
Hi again,

I've found a solution here:
https://stackoverflow.com/questions/22229393/why-is-restsharp-addheaderaccept-application-json-to-a-list-of-item/22230865

the  RestClient.ClearHandlers works for me.
