### ISSUE TITLE
Listing of all methods (like an actual documentation)

### ISSUE THREAD

**Issue by johntiger1** [restsharp/RestSharp#1039]
Temporarily locked out of my google account, so just thought I'd ask: is there a listing of all the methods that RestSharp provides? For example, documentation similar to what you would find on MSDN or the Oracle java docs or unittest for Python. Personally I just want to know if client.execute() is blocking without having to install the package, but I'm just surprised I can't find documentation.

**Comment by alexeyzimarev** [comment]
Well, we have inline documentation for all public methods but we never had generated docs. Shouldn’t be that hard to make although not a priority now.

**Comment by PaulPBath** [comment]
What do you mean by "inline documentation"? If you mean the insights that popup when declaring a method call, then these aren't really sufficient. I was looking to use ExecuteAsync() instead of Execute() and the insights indicate I need an additional callback parameter. Knowing this is not enough without some explanation and/or links to  an example

**Comment by alexeyzimarev** [comment]
Fighting with Vsxmd now... It crashed on RestSharp XML docs. But, I am getting close.
