### ISSUE TITLE
Documentation for Deserialization says "see Customization", but there's no Customization link

### ISSUE THREAD

**Issue by Camios** [restsharp/RestSharp#1087]
## Expected Behavior
if you say "see `something`", the doco should provide a hyperlink to a page containing `something`

## Actual Behavior
"see Customization" doesn't have a hyperlink and there's no results when searching for Customization

## Steps to Reproduce the Problem

  1. Have problem because RestSharp's doco doesn't tell me how to deserialise Json.
  2. Go to https://github.com/restsharp/RestSharp/wiki/Deserialization
  3. No information available and `Customization` information isn't available
  4. Google and some helpful person on stackoverflow has already pointed out setting the ContentType to json using OnBeforeDeserialization

## Specifications

  - Version: n/a
  - Platform: n/a
  - Subsystem: n/a
## StackTrace
n/a

```
Ps, thanks for providing a useful Rest Client API!
```

</details>

**Comment by AddictivKaos** [comment]
It's possible there are two problems here. Other than the missing link. The lack of documentation for handling Json (and other) deserialisation may not be solved by adding the link because I think the link is supposed to actually be an anchor on the same page. Considering adding extra doco for handling non-xml deserialisation by setting ContentType in OnBeforeDeserialization

**Comment by alexeyzimarev** [comment]
I removed that "see Customization" phrase and I think the page contains enough information now: https://github.com/restsharp/RestSharp/wiki/Serialization
