### ISSUE TITLE
Call API how to set the Timeout timeout

### ISSUE THREAD

**Issue by ghd258** [restsharp/RestSharp#1089]
Sometimes the API end method takes a long time to complete, and the UI end call API is out of time. How to solve this problem

**Comment by alexeyzimarev** [comment]
Would be nice if you do not ignore the contribution guidelines when opening an issue.

**Comment by alexeyzimarev** [comment]
Googling "RestSharp timeout" gives you the answer immediately https://stackoverflow.com/questions/46584175/restsharp-timeout-not-working

**Comment by Korporal** [comment]
@alexeyzimarev - That actually doesn't give the answer - it does not make it clear whether we should adjust the client object's timeout or the request object's timeout.

What exactly do the designers of RestSharp recommend here?

**Comment by mnxamdev** [comment]
What @Korporal just said. We're having issues on Xamarin with cancelation tokens not timing out request and also using any of the RestSharp timeout parameters not timing out request. @alexeyzimarev is the proposed solution here to just do the following? If so, did I miss this in the documentation because we just ran through it trying to figure out where we went wrong here with the update causing this bug in our app.

```
try
{
var restResponse = new RestResponse();

var options = new RestClientOptions("baseURL") {
    ThrowOnAnyError = true,
    Timeout = 1000  // 1 second
};
    var client = new RestClient(options);
    //build request
   //ExecuteAsync 
} 
catch (Exception ex)
{
    response.ErrorMessage = ex.Message;
    response.ErrorException = ex;
}

return restResponse; 
```

**Comment by alexeyzimarev** [comment]
ResySharp has two timeout options: `Timeout` and `MaxTimeout`. The `Timeout` option value is passed to the `HttpClient` as a setting. `The `MaxTimeout` value is used when making a call. It works as follows:

Before making the call, the client creates a cancellation token source with the timeout specified in the `MaxTimeout` property. It then creates a linked token source, which links the cancellation token provided for the request by the user (`ExecuteAsync(request, token)`) and the token from the timeout source. The token from the linked source is passed to the `HttpClient.SendAsync`. When `SendAsync` is called, it is up to `HttpClient` to handle the cancellation correctly.

**Comment by alexeyzimarev** [comment]
ResySharp has two timeout options: `Timeout` on the `RestRequest` and `MaxTimeout` on the `RestClient`. The `MaxTimeout` option value is passed to the HttpClient as a setting. The `Timeout` value is used when making a call. It works as follows:

Before making the call, the client creates a cancellation token source with the timeout specified in the `Timeout` property. It then creates a linked token source, which links the cancellation token provided for the request by the user (`ExecuteAsync(request, token)`) and the token from the timeout source. The token from the linked source is passed to the `HttpClient.SendAsync`. When `SendAsync` is called, it is up to HttpClient to handle the cancellation correctly.

```csharp
        using var timeoutCts = new CancellationTokenSource(request.Timeout > 0 ? request.Timeout : int.MaxValue);
        using var cts        = CancellationTokenSource.CreateLinkedTokenSource(timeoutCts.Token, cancellationToken);

        var ct = cts.Token;
        try {
            // skipped
            var responseMessage = await HttpClient.SendAsync(message, request.CompletionOption, ct).ConfigureAwait(false);
           // skipped
        }

```

**Comment by mnxamdev** [comment]
Hi @alexeyzimarev thanks so much for your prompt reply and insight. Sorry if you missed my edited update above. I believe I correctly tried what you suggested.

> UPDATE: I just tried this and it does not work. I have set a 30s timeout on RestClientOptions.MaxTimeout and RestRequest.Timeout and the exception is thrown but not until 2m15s later.

Are you saying there is an issue with the HttpClient Xamarin or Mono implementation here? If so, I can escalate to the proper repo. However, we didn't have these problems until we updated to the latest RestSharp nuget package. I reverted back to v106.15.0 and our custom timeout works as expected. Thanks again for all your efforts and insight, it's greatly appreciated.

**Comment by alexeyzimarev** [comment]
I am not sure where the issues to be honest. RestSharp <107 was using a really awkward way to make async calls, which used another awkwardness of the `HttpWebRequest` wrapper around `HttpClient`. That code has been removed in favour of making async calls with `HttpClient` as intended.

What I tried to explain is that the code for setting the timeouts is very straightforward. I don't see any issue with it, and I have tests that prove it working. It might very well be that the issue is platform-specific. Basically, if `HttpClient` cancels the call when the cancellation token gets cancelled, it should work.
