### ISSUE TITLE
Incorrent nonce generated in 106.3.0

### ISSUE THREAD

**Issue by JacobSMoller** [restsharp/RestSharp#1126]
## Expected Behavior
Before #1121 
Using client.Authenticator = RestSharp.Authenticators
    .OAuth1Authenticator.ForRequestToken(apiKey, apiSecret);  generated a correct nonce

## Actual Behavior
After #1121 generated nonce seems to be invalid. 

## Steps to Reproduce the Problem

  1. Authenticating towards APIs using OAuth1 in 106.3.0 should show the problem.
  2. Works in all previous version i tried (Tested from105.2.3 -> 106.2.2)

## Specifications

  - Version: 106.3.0
  - Platform: Windows 10
  - Subsystem:

**Comment by alexeyzimarev** [comment]
Could you create a test for it so we can avoid regression?

**Comment by alexeyzimarev** [comment]
@JacobSMoller with lack of response, I will have to close this issue soon.

**Comment by alexeyzimarev** [comment]
@mscharrig

**Comment by JacobSMoller** [comment]
@alexeyzimarev  Hey sorry, I have never done anything in C# other than calling our own API once the other day, because a customer complained that it didn't work. 

So I don't really have any clue where to start with doing the test. If you have to close the issue then I understand.

**Comment by JacobSMoller** [comment]
@mscharrig Do you have some means of contacting you privately, keybase perhaps ? :)

**Comment by mscharrig** [comment]
Yeah sure, I just created an account there. Same name as here

**Comment by mscharrig** [comment]
So I just did some testing and found the cause of the bug
​
The nonce is always calculated correct. The exception message is missleading.
The actual problem is one of the RFC3986 signs in a secret, which aren't working with my changes from https://github.com/restsharp/RestSharp/issues/1104
​
secret: "ABCD!"

## Expected Behavior
106.2.2 escaped: "ABCD%21"
## Actual Behavior
106.3.0 escaped: "ABCD%2521"
​
This then leads to an invalid oauth signing key.

**As stated in** https://developer.twitter.com/en/docs/basics/authentication/guides/creating-a-signature.html

"Make sure to percent encode the parameter string! The signature base string should contain exactly 2 ampersand ‘&’ characters. **The percent ‘%’ characters in the parameter string should be encoded as %25 in the signature base string.**"

"The signing key is simply the **percent encoded** consumer secret, followed by an ampersand character ‘&’, followed by the **percent encoded** token secret."

That means RFC3986 signs in secrets should only get escaped once with Uri.EscapeDataString but not with %25. I will implement a fix.

**Comment by alexeyzimarev** [comment]
PR released in 106.3.1
Thanks for reporting!
@mscharrig thanks for fixing!
