### ISSUE TITLE
Deserializing JSON array property returns null

### ISSUE THREAD

**Issue by AKrasheninnikov** [restsharp/RestSharp#1150]
I'm trying to deserialize a JSON object with SimpleJson and it seems to not work as expected. 

## Expected Behavior

```
{
"replynum":0,
"groups":[{"ctime":1516093650769726,"creator":"user@domain.com","id":3335,"name":"some group"}
]}
```

```
    public class GetGroupsResponse
    {
        public int Replynum { get; set; }
        //public GroupInfo[] Groups { get; set; }
        public List<GroupInfo> Groups { get; set; }

        public class GroupInfo
        {
            //[DeserializeAs(Name = "ctime")]
            //public DateTime CreatedTime { get; set; }
            public string Creator { get; set; }
            public int Id { get; set; }
            public string Name { get; set; }
        }
    }
```

`var groups = SimpleJson.SimpleJson.DeserializeObject<GetGroupsResponse>(groupsInfo);`

## Actual Behavior
The Replynum property gets deserialized as expected, but the Groups property is always deserialized as null.

## Specifications

  - Version:
  - Platform: Win 10 .NET 4.6.1
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
Have you tried using an array?
```csharp
public GroupInfo[] Groups { get; set; }
```

**Comment by AKrasheninnikov** [comment]
I have. Didn't work either.

сб, 11 авг. 2018 г., 14:04 Alexey Zimarev <notifications@github.com>:

**Comment by kofaj** [comment]
It's quite old topic but I tried to realized what's gone wrong and:

1. If we take above JSON object and deserialize using :
var groups = SimpleJson.SimpleJson.DeserializeObject<GetGroupsResponse>(groupsInfo);

we'll always receive Replynum property correct even when deserialize process will be not successfull. Replynum property is integer and after creating new GetGroupsResponse object it will recieve value 0 as default. It can be easy tested by changing number to whatever else.

2. After my investigation I found that whole issue is caused by SimpleJson. This library cannot deserialize presented object by internal bug. I used also newtonsoft.json and received correct object. 

Mentioned bug is changing all values from lowercase into uppercase and then another dictionary is trying to parse value from original json object but it cannot pair values due to this first letter.

If you want to check it by yourself, please simply replace first letters in json object into uppercase. It will work


@alexeyzimarev  I think this topic can be closed

**Comment by alexeyzimarev** [comment]
Yeah, SimpleJson is very limited.
