### ISSUE TITLE
OAuth1 signature_invalid when adding query parameters

### ISSUE THREAD

**Issue by zaus** [restsharp/RestSharp#1188]
## Expected Behavior
For requests to authenticate.

## Actual Behavior
OAuth failure message: signature_invalid
I don't think it's related to #1166

## Steps to Reproduce the Problem

  0. `var _client = new RestClient(EtsyApiEndpoint) { Authenticator = OAuth1Authenticator.ForProtectedResource(appKey, appSecret, accessKey, accessSecret) };`
  1. `var req = new RestRequest("/shops/{shopId}/listings/active");`
  2. `req.AddParameter("includes", "Attributes,Inventory");`
  3. `var result = _client.Execute(req);`

## Specifications

  - Version: 106.5.0
  - Platform: Windows
  - Subsystem: Console App?

## Details

I think the problem is at [OAuth1Authenticator.AddOAuthData](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth1Authenticator.cs#L217) (adding get or post params) and [OAuthWorkflow.OAuthWebQueryInfo](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs#L218) (adding querystring params), so request parameters that became part of the querystring are being doubled.  Stepping over the second part during debugging seems to work.

**Comment by KCow** [comment]
This looks like an issue I am now running into. I presume this is related to https://github.com/restsharp/RestSharp/pull/1167 which in the associated commit appears to have changed the logic in the authenticator relating to query parameters (though I could be wrong, but it looks like a recent change to the area in question). 

We have just hit this issue ourselves after upgrading to the latest v106.5.2.0 in our Xamarin Forms project targeted at Android, connecting to a Java/Jersey REST backend on Tomcat 8 using OAuth1. After the update of RestSharp this then breaks all REST calls sent via POST using query parameters sending back a 401 HTTP response after the signature appears to get rejected within Jersey.

e.g.
```
RestRequest tRequest = new RestRequest("/example", Method.POST);
tRequest.AddQueryParameter("extra_parameter", tExtraParameter);
tClient.ExecuteAsync(tRequest, tResponse);
```

Which now returns a 401 Unauthorized when it worked with RestSharp v106.3.1.0, tracing it back in the java, I can see when received in the org.glassfish.jersey.server.oauth1.OAuth1ServerFilter it returns false when it tries to verify the signature:

https://github.com/jersey/jersey/blob/master/security/oauth1-server/src/main/java/org/glassfish/jersey/server/oauth1/OAuth1ServerFilter.java#L226

```
if (!this.verifySignature(osr, params, secrets)) {
  throw this.newUnauthorizedException();
}
```

We've just reverted back to the RestSharp v106.3.1.0 NuGet package until this is resolved / or we understand what the cause is. I'll keep an eye on this issue..

**Comment by zaus** [comment]
@KCow I changed this line (because I'm using `ForProtectedResource`) to the following and it works for me: https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs#L222

            //...unless they were already present at some point, such as being added to the request object
            foreach (var parameter in urlParameters.AllKeys.Where(k => !parameters.Names.Contains(k)))

**Comment by alexeyzimarev** [comment]
@KCow can you do a couple of thing for me? 
- Clone the RestSharp repo, build and add dll directly from the output to your project as a reference
- Try using the suggestion from @zaus and see if it works
- Try bringing back those three lines of code that were removed by #1167 and see if it works

I would also appreciate if you can paste the request if you can trace it in Fiddler (remove the sensitive data of course)

**Comment by artiomchi** [comment]
The only thing changec in #1167 was to include the query string parameters into the `OAuth1Authenticator`. In your snippet, you don't have any query string params in the URL, so the three lines of code that were change shouldn't affect you. 

The query string params that you added are handled separately lower down in code.

To test it without recompiling the project, you can try create the `RestRequest`, passing in the query string params in the url, and see if that fixes the issue. If it doesn't, then the problem is most likely elsewhere (I think) 😄

**Comment by zaus** [comment]
@artiomchi you're suggesting that rather than add query parameters to the request like the following:

    req.AddParameter("includes", "Attributes,Inventory");
    tRequest.AddQueryParameter("extra_parameter", tExtraParameter);

to instead include them directly in the `RestRequest` resource like:

    var req = new RestRequest("/shops/{shopId}/listings/active?includes=Attributes,Inventory&extra_parameter=" + tExtraParameter);

Like I said originally, that should work just like my fix because the former style is causing both the [OAuth1Authenticator.AddOAuthData](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth1Authenticator.cs#L217) and [OAuthWorkflow.OAuthWebQueryInfo](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs#L218) to include the querystring parameters (one gets from the parameter collection while the other scrapes it from the url querystring, thus getting the same query params twice) when creating the OAuth signature.

I've confirmed this to be the case with something like the following:

    var url = "/blahblahblah";
    var qs = new NameValueCollection();
    qs.Add("param1", "value1");  // normally: req.AddParameter("param1", "value1");
    url += "?" + string.Join("&",
				qs.AllKeys.Select(a => a + "=" + HttpUtility.UrlEncode(qs[a])));
    var req = new RestRequest(url);
    _client.Execute(req); // doesn't return signature error

However....this is a workaround, and the bug remains.

To reiterate, the problem is because:

* [OAuth1Authenticator.AddOAuthData](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth1Authenticator.cs#L217) is building the `WebParameterCollection` from the request parameters (which includes GET url parameters added via `request.AddParameter(...)`)
* The same method call constructs the full request url [which includes those GET parameters added to the request object](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth1Authenticator.cs#L196)
* [OAuthWorkflow.OAuthWebQueryInfo](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs#L218) is parsing the request URL (which had already attached the GET parameters as querystring params as indicated) in order to add the querystring parameters to the `WebParameterCollection`, thus adding the querystring parameters TWICE
* therefore the signature is incorrect because it's got twice as many querystring parameters registered as actually provided

**Comment by zaus** [comment]
...so another option to fix it may be to exclude get and querystring parameters when [initially building the `WebParameterCollection` here?](https://github.com/restsharp/RestSharp/blob/a39f28e230df7ff60bcec4e9bf54d9335a130e74/RestSharp/Authenticators/OAuth1Authenticator.cs#L217).

**Comment by zaus** [comment]
Sorry, this is why I don't really like pull requests -- I feel I'm overstepping my reach by magically being able to commit to your repo.

**Comment by artiomchi** [comment]
@zaus Great bit of investigation there! I haven't realised that the `BuildUri` method picked up the query parameters added using `AddParameter`, which causes them to be added twice in the hashing code!

**Comment by artiomchi** [comment]
I forgot to add - I don't think you're overstepping any bounds at all. In fact, isn't this what open source is all about? Making it possible for anyone to contribute to the project?

In the end - you can't commit to the main repo without peer approval - which is the point of pull requests :)

**Comment by zaus** [comment]
@artiomchi okay good, it mentioned something like "this request is eligible for automatic merging" so just wanted to make sure.  (I'm new to pull requests)

**Comment by alexeyzimarev** [comment]
I will still look at it before merging :) Automatic merging means that there are no merge conflicts, nothing more.

**Comment by alexeyzimarev** [comment]
@zaus @artiomchi 
I have the following comments/suggestion:

1) The code that was removed #1167 was working correctly. It was addressing this very issue.
2) The issue that #1167 was fixing is not a real issue. It looks more like an incorrect usage of the parameters. Adding default query string parameter to the client would solve it and the code change won't be necessary.
3) The issue was mainly caused by the fact that the client accepted query string parameters in the base URL, which breaks the OAuth1 authentication.
4) The correct solution would be to prevent it from happening, by throwing an exception when the client is used with query string parameters in the base URL and with OAuth1.

I have the code ready. Please let me know if you agree.

**Comment by artiomchi** [comment]
Hi @alexeyzimarev,

I see your point, but I'll have to only partly agree with you, I think.

* After this discussion, I can see that the change in #1167 was the wrong thing to do.  _but..._
* It was trying to fix a real issue. I wasn't trying to add query string parameters to the **base** url, I was trying to make a new request, passing in query string params in the request url
* > the client accepted query string parameters in the base URL, which breaks the OAuth1 authentication.

  Umm.. Wouldn't the OAuth1 spec would describe protocol, and **not** the client implementation? I genuinely don't know, so just asking it here
* Obviously the client could throw an exception if you pass query string params to the `RestRequest` constructor, but wouldn't it be better to parse them instead, and add them as query parameters in the constructor?

   Again, we're not talking about the base url, I'm wondering if the `RestRequest` constructor should be able to parse query string params and handle them properly?

If you think that it shouldn't support that, then that's fine too, I guess. But it should be explicit about it

**Comment by alexeyzimarev** [comment]
@artiomchi I got your comment by email, have you deleted it? I see our point, I wasn't sure what you did exactly. I am not sure why do we need to parse parameters in the request URL since we offer enough options to add query parameters using `AddParameter` and `AddQueryParameter`. Notice that all those methods support fluent-style configuration so your code looks clean:

```csharp
var client = new RestClient("https://whatever.com/api");

//

var request = new RestRequest("gimmethat").
    .AddQueryParameter("id", id)
    .AddQueryParameter("page", 10);

var result = await client.GetAsync<Result>(request);
```

If you think we need to parse the query that you specify in the request constructor, we need to move this logic to the constructor:
 - Build the full URL without query parameters that are added by `AddParameter`
 - Parse the query and get all parameters
 - Remove parameters from the query
 - Add parameters to the parameter list

That would be a proper solution, but it has some complexity like finding out the request part of the full URL when parsing.

Please don't think I am criticising you for the PR, I love when the community contributes to solving issues. But right now I think we broke more than we solved and I must revert the change for the sake of being compatible with what we had before for the majority of users. And, since I added an exception to the OAuth workflow, people won't spend as much time as you did, trying to figure out why the signature is eventually wrong when they use query parameters in both client or request URL. Do you think it makes sense?

**Comment by artiomchi** [comment]
@alexeyzimarev No, I completely agree with you. Looking back on it, I see that my original PR actually broke the intended behaviour. I also can see now the `AddQueryParameter` method, but I think the library should also allow query params passed in the resource url (but not in the base url, of course).

P.S. Seems like GitHub is having issues with their storage, which is why the comment wasn't visible for some time :)

https://status.github.com/

**Comment by alexeyzimarev** [comment]
I believe there is a problem on Github right now since I don't see recent comments, but email seems to work.

**Comment by alexeyzimarev** [comment]
@artiomchi (https://link.getmailspring.com/link/1540206710.local-0e65a1bd-54bb-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fartiomchi&recipient=cmVwbHkrMDAyYjBjNTVhMTQzYjA1ZTZiYzYwZTJjZGE3Mzk1ZjJmYTYxZWNhMWUwYTkzODhmOTJjZjAwMDAwMDAxMTdlNTcxZWI5MmExNjljZTE1ZjNmNTM1QHJlcGx5LmdpdGh1Yi5jb20%3D) I agree that we need to fix it, I'd like to fix it in a way I described in my earlier comment - by parsing the client+request URL and move all parameters from there to the parameters list. It will solve all issues. I want to make a new version with reverting the behaviour, returning to the point where we were, then do a proper fix in the new version. Unfortunately, no comments are being shown in the issue, I will hold on until it is fixed and people can look at the proposal.

**Comment by artiomchi** [comment]
Sure, sounds good!

**Comment by sescandell** [comment]
Hi there,

Don't know why this issue has been closed, but the issue is still there.

Using RestSharp 106.5.4 the following code will fail:

```csharp
var client =  new RestClient("https://api.xing.com")
            {
                Authenticator = OAuth1Authenticator.ForProtectedResource(<ConsumerKey>,<ConsumerSecret>,<AccessToken>,<AccessTokenSecret>)
            };
 var request = new RestRequest(XingEndpoints.UsersMeContacts);
request.Method = Method.GET;
request.AddQueryParameter("limit", "0"); // Same with request.AddParameter
var response = client.Execute(request);

```

Returning a signature error response.

While the following works as expected:

```csharp
var client =  new RestClient("https://api.xing.com")
            {
                Authenticator = OAuth1Authenticator.ForProtectedResource(<ConsumerKey>,<ConsumerSecret>,<AccessToken>,<AccessTokenSecret>)
            };
 var request = new RestRequest(XingEndpoints.UsersMeContacts + "?limit=0");
request.Method = Method.GET;
var response = client.Execute(request);

```

Did I missed something (tried to follow all issues and PR about this subject but get lost 😄 )?

Thanks for your time,

**Comment by jasond-s** [comment]
@alexeyzimarev I have run into the same issue as @sescandell in our usage of RestSharp. Are we doing something wrong?

**Comment by alexeyzimarev** [comment]
I am not using OAuth1 personally and it is hard to test. People were doing PRs to solve their issues, but things might have got broken on the go. It is hard for me to say what is wrong. It would be nice if someone takes care of fixing it.
