### ISSUE TITLE
How do I use my access token?

### ISSUE THREAD

**Issue by apostrophesoftware** [restsharp/RestSharp#1211]
I have a web api that requires an access token for authentication.  I have been able to to RestClient to retrieve the access token, I am now confused as how to provide the access token when I call methods.

I have tried the following code and get Unauthorized returned

```
RestClient docClient = new RestClient("https://localhost:44325/");
docClient.AddDefaultParameter("Id", "1");
docClient.Authenticator = new OAuth2AuthorizationRequestHeaderAuthenticator(accessToken.AccessToken);

docClient.Authenticator.Authenticate(docClient, docRequest);
response = docClient.Execute(docRequest);

```

I am a bit lost, I have asked Google but cannot find an answer!

**Comment by alexeyzimarev** [comment]
I believe that you get better help on StackOverflow.

**Comment by apostrophesoftware** [comment]
thanks!

**Comment by Hoang-Minh** [comment]
Pass the token to the client.

var client = new RestClient("uri");
var authentication = new JwtAuthenticator(<your token value>);
client.Authenticator = authentication;

// How to execute your api:
var request = new RestRequest(METHOD.GET);
client.Execute(request);

**Comment by HelmerDenDekker** [comment]
I know this is closed, but having the same question and coming to think about it, shouldn't you add the token to the request instead of the client? The token will be refreshed, probably, since it is an accesstoken... So it would be better to add it to the request using request.AddHeader("authorization", "bearer "+ accessToken) in my opinion.
Sidenote: Of course this depends on how you instantiate and use the RestClient (lifecycle-wise)
