### ISSUE TITLE
ResponseStatus - enum values are unclear

### ISSUE THREAD

**Issue by dimacurotech** [restsharp/RestSharp#1243]
https://github.com/restsharp/RestSharp/blob/26e49d71079623e8ee5025fe697cd68af1053c6e/RestSharp/Enum.cs#L77

It is completely unclear how values of ResponseStatus enum should be treated.
In particular: 

- what is None? 
- what is Completed? Does completed means a completed request, no matter what is the HTTP status code? Or do only 2xx/3xx responses count as completed?
- what is Error: is it 404 HTTP status code or is it response parse error? Or is it network failure? Or is it deserialization error?

We can read the source code every time we need to remember what do these values mean, but wouldn't it be better to add XML comments with good explanation to every enum value?
Currently ResponseStatus values are **not** self-explanatory.

**Comment by greendimka** [comment]
Would love to do it, maybe will do it latet. Currently I am not sure about the differences between None, Completed and Error.

**Comment by dimacurotech** [comment]
I wonder if some of maintainers can give a solid explanation on the ideas behind each of the enum values?

**Comment by alexeyzimarev** [comment]
A quick look at the code shows that:

- `None` is the default value, set when the request has not been executed yet
- `Completed` is set when we get any kind of response and not getting any errors with further extracting the response
- `Error` is set when we get an error during the request execution (network failures, etc) if we can extract the response data or we can't deserialize the response.
- `Timeout` happens when the request is not completed during the given timeout

**Comment by alexeyzimarev** [comment]
It is actually in the docs: https://github.com/restsharp/RestSharp/wiki/Getting-Started#note-about-error-handling
