### ISSUE TITLE
Content of response is empty for a BadRequest, even if there is response, weird status code. Newest version

### ISSUE THREAD

**Issue by grzegorzociepka** [restsharp/RestSharp#1280]
> I'm using RestSharp, and while I do have bad request (400) with POST request, I cant see response, it's empty.
On fiddler I can see that there is message.

It was mine previous post. I've downloaded latest version (released 2 days ago) and there is different problem.
Now it is returning Status Code 0(fiddler shows 400) and ErrorMessage: 
"Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null.\nParameter name: src"

**Comment by alexeyzimarev** [comment]
Can you check what is the "last version" exactly? The last version before today on nuget.org was 106.6.7, released a month ago. I published the 106.6.8, where this issue was fixed, just today. There was no version that was released this week before today.

**Comment by grzegorzociepka** [comment]
106.6.8 downloaded directly from this git.

**Comment by alexeyzimarev** [comment]
I don't think it is related to Xamarin. Thanks for reporting, I will check. Need to find some place that will give me an error when calling :)

**Comment by Phyxion** [comment]
I also have an issue with 106.6.9, I'm returning 200=OK on server and empty response (null), 106.6.7 works OK. This new version doesn't work correctly anymore as it sets ErrorException to {"Object reference not set to an instance of an object."}.

This is all I have in stack trace of exception:
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)

**Comment by axa88** [comment]
My 2cents, this didnt start with the latest version, Ive found that Ive personally needed to entirely remove any use of ExecuteTaskAsync and ExectueAsync as far back as 106.3.1 i believe, as many non 200 responses would simply fail with the same error message "Value cannot be null.\nParameter name: src"

Digging into it one day i found a System.Net.WebException where it was choking on a System.Buffer.BlockCopy 

Making the same calls with the non-async version 'Execute' wrapped in a task solved my problem but i can reproduce this like clockwork using the async versions stated in each recent 106.6.7, 106.6.9 

I got past it but did kept a screenshot of the debugger attached, and the header of the offending response, maybe it could help solve the issue.

fwiw i was also using RestSharp in Xamarin, 

![image](https://user-images.githubusercontent.com/13371986/53771762-dbd7d780-3eb1-11e9-9c8c-311f5b1e117d.png)


HTTP/1.1 409 Conflict
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, must-revalidate, private
Cache-Control: private
Pragma: no-cache
Set-Cookie: TRACKID=336cd0d6c4c856429491c13bfab85b4b; Path=/; Version=1; httponly
Transfer-Encoding: chunked
X-AspNet-Version: 4.0.30319
Content-Type: application/json
Date: Tue, 05 Mar 2019 00:23:20 GMT
Server: Redacted Webserver

**Comment by axa88** [comment]
is this not the same issue as this:

https://github.com/mono/mono/issues/9511

**Comment by alexeyzimarev** [comment]
It would be nice to get some repro. I was going through tests and when an exception is thrown, I always got an error response. I saw a couple of suspicious places where I could imagine something wrong happening with propagating exceptions and fixed those. I also added the `ThrowOnAnyError` property (false by default), which will just throw instead of swallowing exceptions and populating error responses.

It is all in the latest version.

**Comment by alexeyzimarev** [comment]
Indeed there was an issue in Mono but we also did some changes around exception handling. If you experience this issue still with the latest version, please reopen the issue. I am closing it for now.

**Comment by Phyxion** [comment]
My problem still exists @alexeyzimarev in latest NuGet version, same as https://github.com/restsharp/RestSharp/issues/1280#issuecomment-469277188

` at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)`

StatusCode is OK, but `ErrorException` is set to `NullReferenceException`, with above stack trace.

This is NOT under Mono but .NET Framework. 106.6.7 is last version that is OK.

**Comment by alexeyzimarev** [comment]
@Phyxion it would really help to get anything more than that, for example, the content of the response and the contract of your expected response type.

**Comment by Phyxion** [comment]
Thought I'd added that already. Here's a little more then 🙂

The server returns `null` (not as a string or anything, just no body /  Content-Length: 0) and status 200. That's it really. Called like `Client.ExecuteAsync<object>(request)`. In 106.6.7 `response.Data` is correctly returning `null`.

**Comment by alexeyzimarev** [comment]
aha, I see. It is a different issue actually, already reported https://github.com/restsharp/RestSharp/issues/1419

The `RestClient` class has a non-generic overload `ExecuteAsync(IRequestRequest request, CancellationToken cancellationToken = default)`, which you should be using instead of the generic overload since you don't expect a request body back. But this overload is missing from the `IRestClient` interface. I already fixed it. You can use the obsolete `ExecuteTaskAsync` with the same signature until the next version is released.

**Comment by Phyxion** [comment]
I've already tried ExecuteTaskAsync, it has the same problem. I don't know for certain if the server returns no body, hence I'd like it to return an object.

Furthermore, I've been debugging this and noticed that if you return null, the Content-Length in RestSharp is detected as -1 instead of 0. Going through some responses _with content_ the ContentLength in RestSharp ain't correct either, it's also almost always -1?

But the problem I encountered was actually here:
https://github.com/restsharp/RestSharp/blob/0dc0a799497b07bc67ffac47e34e87b9e0e86696/src/RestSharp/RestClient.cs#L676
`GetHandler(raw.ContentType)` can return null, but this func is immediately executed regardless if `GetHandler(raw.ContentType)` returned null or not.
Something along the lines of this fixes my problem:

> var func = GetHandler(raw.ContentType);
var handler = func?.Invoke();

I'll submit a PR for this.
