### ISSUE TITLE
Request not sent out intermittently and timeout not working as expected

### ISSUE THREAD

**Issue by mdfaizali390** [restsharp/RestSharp#1319]
## Actual Behavior
I am sending calling rest api with timeout = 3 seconds. For some reason, when i start my application and send request, Request is not not sent out (verified from Wireshark). This is intermittent (3/7 times reproducible)

## Steps to Reproduce the Problem

url = http://174.129.47.12:5000/search/number=''&&todate='2019-05-25'&&fromdate='2019-04-29' 
var client = new RestSharp.RestClient(url);
client.Timeout = 3000;
var response = client.Execute<List<CallDataDTO>>(new RestRequest());

No Exception raised. Application stalls. 
I am using newtwonsoft JSON to de-serialize JSON to object.
What i expect is, even when request is not sent out, timeout should work because its stalling my whole application currently 

## Specifications

  - Version: 106.6.9.0
  - Platform: Windows 7

</details>

**Comment by mdfaizali390** [comment]
Is there any way i can share enable debug and share logs?

**Comment by alexeyzimarev** [comment]
We use sourcelink so it should be easy to debug.

**Comment by bhatnagarsaddy** [comment]
@alexeyzimarev @mdfaizali390  Did you guys find any solution for this one???

**Comment by alexeyzimarev** [comment]
We set the request timeout and the rest is handled by .NET. I think this issue is _very easy_ to fix on the other side by using async calls instead. There, we schedule the cancellation request for the cancellation token source after timeout expires and it should always work because it doesn't depend on how the WebRequest handles timeouts.
