### ISSUE TITLE
Repeated requests are slower under NetCore 3.1 than under NetFramework

### ISSUE THREAD

**Issue by HeilOliver** [restsharp/RestSharp#1396]
In a WPF application (Net 4.7.2) the first request takes some time (in my case about 2 seconds) to return a result. If the request is repeated, the time is drastically reduced (in my case to about 10ms). Under NetCore 3.1 all requests need about two seconds.
Whether the client is instantiated as a singltone or always new doesn't matter.

_Code for measuring the request response time_
```csharp
var restClient = new RestClient("https://localhost:10600");
var versionRequest = new RestRequest("/api/v1/Status/Version", Method.GET);
var stopwatch = new Stopwatch();

stopwatch.Start();
restClient.Execute(versionRequest);
stopwatch.Stop();

Debug.WriteLine($"{stopwatch.ElapsedMilliseconds} ms");
```

## Expected Behavior
A NetCore application should have the same behavior as a NetFramework application

## Actual Behavior
A NetCore application is dramatically slower in repetitive requests.

## Steps to Reproduce the Problem

  1. Create a WPF Application in NetCore and NetFramework 
  2. Include Restsharp
  3. Make an Api Request and measure the time
  4. Repeat the procedure

## Specifications

  - Version: 106.9.0
  - Platform: Windows 10 Pro - 1909
  - NetCore Version: 3.1.100
  - NetFramework Version: v4.7.2
  - NetFramework CLR Version: v4.0.30319

**Comment by ngbrown** [comment]
I just had this exact problem.  Every request took 2 seconds to `localhost`.

At first I thought it was a proxy, because starting up Fiddler made the time drop down to the expected x ms.

I eventually came across [this StackOverflow question](https://stackoverflow.com/q/15465203/25182) that pointed me to change `localhost` to `127.0.0.1`.  This fixed it.

It appears that RestSharp is preferring to attempt IPv6 first, then times out and attempts to reconnect with IPv4.
