### ISSUE TITLE
ExecuteAsync Does Not Fully Replace ExecuteTaskAsync

### ISSUE THREAD

**Issue by stricq** [restsharp/RestSharp#1419]
## Expected Behavior
Prior to 106.10.1, following code returns a `Task<IRestResponse>`

`Client.ExecuteTaskAsync(request);`

Now that 106.10.1 has marked ExecuteTaskAsync as obsolete, following code is expected to also return `Task<IRestResponse>`

`Client.ExecuteAsync(request);`

## Actual Behavior

Instead, following code produces a compilation error:

`Client.ExecuteAsync(request);`

Error	CS0411	The type arguments for method '`IRestClient.ExecuteAsync<T>(IRestRequest, CancellationToken)`' cannot be inferred from the usage. Try specifying the type arguments explicitly.

I have found that following code does compile and returns `Task<IRestResponse>`

`Client.ExecuteAsync(request, request.Method);`

## Steps to Reproduce the Problem

  1. Write code as above, see compilation error.

## Specifications

  - Version: 106.10.1
  - Platform: ASP.Net Core 3.1

**Comment by alexeyzimarev** [comment]
Just yesterday I changed all the tests to use ExecuteAsync where ExecuteTaskAsync was previously used. There were no problems with compiling the code.

Can you provide more code?

**Comment by oddeirik** [comment]
Can confirm. There used to be an interface definition
`IRestClient.ExecuteTaskAsync(IRestRequest)`, but in v106.10.1 this is marked as obsolete by `IRestClient.ExecuteAsync`.

However, there is no direct replacement for the `IRestClient.ExecuteTaskAsync(IRestRequest)` interface method. The closest one is `IRestClient.ExecuteTaskAsync(IRestRequest, Method)` as stricq mentions, where you also have to specify the HTTP Method.

This isn't a big deal, but if the method is already a part of the request, surely having an interface definition that reads it from the request makes sense? Especially since it was defined that way in the now obsoleted method 😃

**Comment by alexeyzimarev** [comment]
I found the issue. The `ExecuteAsync` non-generic overload that returns `IRestRequest` is not a part of the interface, but it is available on the `RestClient`. I already fixed it locally.

**Comment by alexeyzimarev** [comment]
https://bitbucket.org/farmas/atlassian.net-sdk/issues/499/please-recompile-using-restsharp-106100

**Comment by stricq** [comment]
Any estimate for the next release time?

**Comment by alexeyzimarev** [comment]
Closing because of the latest release.

**Comment by NXTwoThou** [comment]
> Can confirm. There used to be an interface definition `IRestClient.ExecuteTaskAsync(IRestRequest)`, but in v106.10.1 this is marked as obsolete by `IRestClient.ExecuteAsync`.
> 
> However, there is no direct replacement for the `IRestClient.ExecuteTaskAsync(IRestRequest)` interface method. The closest one is `IRestClient.ExecuteTaskAsync(IRestRequest, Method)` as stricq mentions, where you also have to specify the HTTP Method.
> 
> This isn't a big deal, but if the method is already a part of the request, surely having an interface definition that reads it from the request makes sense? Especially since it was defined that way in the now obsoleted method 😃

This has cropped back up.  I went looking for why switching to 110.2.1-alpha.0.16 gave me an error in some legacy code.  By trying different versions, looks like it was a change in 110.2.1-alpha.0.7. 

// v110.2.1-alpha.0.6 and below
var rest = new RestRequest(endpoint, Method.Put);
var response = client.Execute(rest);
// v110.2.1-alpha.0.7 and above
var rest = new RestRequest(endpoint, Method.Put);
var response = client.Execute(rest, rest.Method);

Seems silly since it should be able to be retrieved from RestRequest(as it was previously), but, whatever, easy code change.  Just posting this in case someone else goes searching like I did.

**Comment by alexeyzimarev** [comment]
I am not sure when and where the change happened, but I am happy to add an `Execute` extension without the method argument.
