### ISSUE TITLE
Ability to add middleware to act on IRestRequest and IRestResponse

### ISSUE THREAD

**Issue by Ducatel** [restsharp/RestSharp#1432]
Hi everyone,

There is an official way to add some "middleware" which are able to act on `IRestRequest` and `IRestResponse` ?

This is useful when for example, you need to inject/extract CSRF token in/from each request/response.

Thanks

Ps: I find [this repos](https://github.com/HelloKitty/GladNet.ASP.Client/tree/master/src/GladNet.ASP.Client.RestSharp/Middleware) which made some interface management of middleware.

**Comment by alexeyzimarev** [comment]
We have `OnBeforeRequest`, which is called right before making the request and `OnBeforeDeserialization`, which is called after the response is received and before deserializing it.

Does it cover your use-case?

**Comment by Ducatel** [comment]
Hi,

Not really, because:

- `OnBeforeRequest` and `OnBeforeDeserialization` are on `RestRequest` but should be on `RestClient`. (Code must be execute for all query in my case. I can handle the case when the CSRF are not present)

- `OnBeforeDeserialization` is too soon, it will be easy to extract csrf token right after the deserialization.


Maybe a middleware management functionality can be added to RestSharp ?
There is an example of that feature in [Guzzle PHP library ](http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#middleware)(which are also a REST client API)

**Comment by alexeyzimarev** [comment]
Ok, I see that adding those callbacks to each request is troublesome. But I am trying to find out at what stage to you plan to engage the middleware? For example, you found out that calling it before the deserialisation step is too early. But we return the result right after deserialising it. So, the question is what do you want to get access to? What do you think can be wrapped in the middleware call?

**Comment by Ducatel** [comment]
Ok, so I can tell you what I already face in different language.

Quite often you have 2 type of interfaces exposed to customer:

- The first one is the one which will be called right before the execution of the HTTP query (probably [just here](https://github.com/restsharp/RestSharp/blob/7d71ac52bbc1cc697d7fa54e3b9630723f499f07/src/RestSharp/RestClient.Sync.cs#L115) I think). This interface, take a request object and return the updated request object. (Quite often the request/response are immutable object so, that we there is a return)

- The second one is the one which will be called right after the HTTP query (probably [just after here](https://github.com/restsharp/RestSharp/blob/7d71ac52bbc1cc697d7fa54e3b9630723f499f07/src/RestSharp/RestClient.Sync.cs#L117)). Also It take a response in param and return the updated response.

Internally you should manage a 2 list of middleware.( One for the "on query" and another for the "on response". ) You should execute theses middleware in the order where it was added by the user. 

So for me, in theses middlware, the serialization should be done before. The user will probably want to work with parsed object, not with raw body, header, etc.... (but you can also added some Raw middleware interface if you want ;) )

I hope I'm a little bite clearer now :D

**Comment by alexeyzimarev** [comment]
I am not sure if the link in the issue (https://github.com/HelloKitty/GladNet.ASP.Client/blob/master/src/GladNet.ASP.Client.RestSharp/Middleware/IRestSharpMiddleWare.cs) actually represents a concept of middleware.

There's a request execution flow and adding a middleware would allow placing some code to become part of the request execution pipeline. So, it would need to call something like `Next(request)` to let the request go further. When the request is executed, the result comes back to the middleware, logically. So you can manipulate the result. Request middleware would easily allow things like retries, circuit breakers and so on. Even deserialization could be done as a middleware.

So, all that seems fine but there's no such thing as the result pipeline, simply because the response itself is the result of the request pipeline execution.

But, deserialization could potentially be modeled as a pipeline itself.

It doesn't seem like a five minutes job for me. I need to think about it.

**Comment by Ducatel** [comment]
> There's a request execution flow and adding a middleware would allow placing some code to become part of the request execution pipeline. So, it would need to call something like Next(request) to let the request go further. When the request is executed, the result comes back to the middleware, logically. So you can manipulate the result. Request middleware would easily allow things like retries, circuit breakers and so on. Even deserialization could be done as a middleware.

Yes, exactly. This is how PHP guzzle lib implements the middleware ;)

> It doesn't seem like a five minutes job for me. I need to think about it.
I don't know your code so, I'm not able to determine that :p
