### ISSUE TITLE
Wrongly deserialized DateTime format “yyyy-MM-ddTHH:mm:ssZ

### ISSUE THREAD

**Issue by szamacz** [restsharp/RestSharp#1433]
## Expected Behavior
When deserializing date format  “2020-02-02T10:00:110Z" date should be deserialized as  “2020-02-02T10:00:110" UTC time.

## Actual Behavior
Because last digit i 0, date is deserialized as “2020-02-02T10:00:11" and its not taken as UTC time but local one. Therefore in other than UTC time zone its providing wrong time (difference in hours)

## Steps to Reproduce the Problem

Deserialize API response with date contains format “yyyy-MM-ddTHH:mm:ssZ using **Data** from **interface IRestResponse<T>**

## Specifications

  - Version:  106.10.1
  - Platform: .NET Standard 2.0 and .NET Framework 4.6.1
  - Subsystem: Windows 10

**Comment by nesc58** [comment]
The problem occurs when your serialization does not match your deserialization.
The supported date time formats are listed here: https://github.com/restsharp/RestSharp/wiki/Serialization#jsondeserializer-3
The wiki page differs from implementation because the format "yyyy-MM-dd-THH:mm:ss.fffZ" is not listed but implemented: https://github.com/restsharp/RestSharp/blob/master/src/RestSharp/Extensions/StringExtensions.cs#L158

I assume you serialize date time with the format "yyyy-MM-ddTHH:mm:ss.FFFFFFFZ". This does not match to the listed / implemented ones.

The format "yyyy-MM-ddTHH:mm:ss.FFFFFFFZ" is the default one of ASP.Net Core and Newtonsoft.Json bzw not the default or implemented one of RestSharp. 

When you deserialize "2020-02-02T10:00:110Z" it is actually “2020-02-02T10:00:110" UTC time.
When you try to deserialize "2020-02-02T10:00:11Z" it is something in current local time.

We run in the same issue because we serializes date time as "yyyy-MM-ddTHH:mm:ss.FFFFFFFZ". By changing the serializer of rest sharp from "yyyy-MM-ddTHH:mm:ss.fffZ" to "yyyy-MM-ddTHH:mm:ss.FFFFFFFZ" the problem was solved for us.

We fixed this by adding:
client.UseSerializer(() => new JsonSerializer { DateFormat = "yyyy-MM-ddTHH:mm:ss.FFFFFFFZ" });

Please try to set you custom date time string.

**Comment by alexeyzimarev** [comment]
@nesc58 thank you for the detailed explanation. I'd afraid fixing it in SimpleJson will break a lot of applications that rely on the current behaviour.

I'd suggest using the custom `DateFormat` as advised, maybe I can put it in the documentation. Alternatively, choose one of the available serialisers: https://restsharp.dev/usage/serialization.html#system-text-json
