### ISSUE TITLE
Implement rate limiting parameters

### ISSUE THREAD

**Issue by xantari** [restsharp/RestSharp#1465]
## Expected Behavior

Rate limiting is a common occurence with API's. For instance Zoom sets rate rate limits depending on your plan: https://marketplace.zoom.us/docs/api-reference/rate-limits

Add functionality to allow for rate limiting to RestSharp.

**Comment by alexeyzimarev** [comment]
Rate limiting is the server responsibility, why would you want to push this to the client? How exactly do you see the client to do rate limiting? You are using the client in your application and you have full control on how often you call.

**Comment by xantari** [comment]
From my understanding if you hit Zoom's API too many times you will start to get failures. (correct me if I'm wrong here).

What then will happen is your call will fail.

Folks apparently use something like Polly (nuget) to implement rate limiting and retry policies.

**Comment by alexeyzimarev** [comment]
That's correct, any API that applies rate-limiting return a specific error (don't remember which one) and it's for the API consumer to use some sort of circuit-breaker. Polly is widely used, including HttpClient. Since it's up to the API consumer to decide how to handle such cases, I can hardly imagine how and why this functionality can be embedded into RestSharp.

**Comment by xantari** [comment]
Is there a way to have restsharp obey a polly policy?

**Comment by alexeyzimarev** [comment]
Polly is a wrapper. You define a policy and wrap RestSharp calls with the policy execution and it all works. Polly is generic and can be used with anything.

**Comment by xantari** [comment]
Ok, if that’s the case I’ll close
