### ISSUE TITLE
Need an IAuthenticater.AuthenticateAsync

### ISSUE THREAD

**Issue by jim-lightfoot** [restsharp/RestSharp#1468]
Need an async version of IAuthenticater.Authenticate. Need to be able call external APIs for authorization and that requires using async. Using "GetAwaiter().GetResult()" is a very bad practice.

**Comment by alexeyzimarev** [comment]
I agree that we might need it but I don't agree that using `GetAwaiter().GetResult()` is a _very bad_ practice. It's not ideal but that how async code should be called from the sync code.

**Comment by jim-lightfoot** [comment]
OK. "very bad" is a little strong but should be avoided:

**Comment by alexeyzimarev** [comment]
Yeah, I can cite the article there

> In general, I try my best to avoid synchronously blocking on an asynchronous task. However, there are a handful of situations where I do violate that guideline. In those rare conditions, my preferred method is GetAwaiter().GetResult() because it preserves the task exceptions instead of wrapping them in an AggregateException.

I agree that we should've made the call asynchronous but I have to figure out how to change it without breaking the existing API.

**Comment by mhornbacher** [comment]
@jim-lightfoot Would the `AuthenticateAsync` method not need to call `GetAwaiter().GetResult()` if called synchronously by user code (e.g. in a `client.Execute` call?) Or perhaps it should only run on async methods (e.g. `client.ExecuteAsync`)?

**Comment by jim-lightfoot** [comment]
I would think there would be both an Authenticate and AuthenticateAsync version so that if the calling code is not async it call the the sync Authenticate version.

**Comment by mhornbacher** [comment]
Should `ExecuteAsync` not call `Authenticate`?

Perhaps it could fallback to it by default? Perhaps something like this (C# 8+, not supported)

```
public interface IAuthenticator
{
    void Authenticate(IRestRequest request);
    Task AuthenticateAsync(IRestRequest request) => Task.FromResult(Authenticate(request));
}
```

**Comment by jim-lightfoot** [comment]
Yes, that could certainly be the default implementation. The key is I want to implement my own IAuthenticator and I want the RestSharp code to call my async version.

**Comment by tgolla** [comment]
In recently looking at adding a custom authenticator I’ve come across the same issue of needing an async version of IAuthenticater.Authenticate to call an authentication services we have written as async.  I have been down the rabbit hole of how I might run an async method in a non-async interface method  (https://stackoverflow.com/questions/9343594/how-to-call-asynchronous-method-from-synchronous-method-in-c) and ultimately found my way to the async holy grail of making an async call from a class constructor (https://stackoverflow.com/questions/23048285/call-asynchronous-method-in-constructor).

In a temporary fix I have created an async extension method to the RestRequest class, but this requires that it is called each time you build a request.  I considered an async extension method for the RestClient class, but since we instantiate our RestClient classes in our service constructors that get injected through DI in to our ASP.NET API controllers there is simply no way to fire the async extension method in the constructor. This leaves placing the extension method call in each API method, which is no better than the async extension method to the RestRequest class solution.

Looking over this thread the solution I see is as follows.

Add the following IAuthenticatorAsync interface.

public interface IAuthenticatorAsync
{
    Task AuthenticatorAsync (IRestClient client, IRestRequest request);
}

In the RestClient class add the following property.

public IAuthenticatorAsync AuthenticatorAsync { get; set; }

In the executing logic of the RestClient class implement the following.

- If the execute call is async, call AuthenticatorAsync if defined.  If not defined call the non-async Authenticator if defined.
 
- If the execute call is not async just call the non-async Authenticator if defined.  Don’t try to make some heroic attempt to call the AuthenticatorAsync method if defined.

This implementation also allows the code to remain backwards compatible as you are not modifying IAuthenticator.

**Comment by tgolla** [comment]
Please do not close as I am certain there are others who would like to see this addressed so we can stop using extension methods work arounds on the RestClient every time we make a call.

**Comment by mhornbacher** [comment]
Hu, Perhaps I'll take a crack at it this week. Those specs seem nice and solid :)

**Comment by mhornbacher** [comment]
Ha, looks like this is blocked by making `RestClient.Async.cs` use `Task`s :)

**Comment by pankaj-nikam** [comment]
It would have been nice if the feature was there :)
Thanks for considering this.

**Comment by alexeyzimarev** [comment]
In v107 `IAuthenticator` needs to return `ValueTask` and we will await it.

**Comment by mhornbacher** [comment]
Nice! Big fan of this breaking change :)

Why not allow it to just return a Task though and leave the `ValueTask` optimization to callers?

**Comment by alexeyzimarev** [comment]
As a rule of thumb if the primary use case will be synchronous, returning a `Task` leads to excessive allocations. Using `ValueTask` allows asynchronous operations without unnecessary burden for consumers.
