### ISSUE TITLE
Error when trying to deserialize JSON

### ISSUE THREAD

**Issue by burekas7** [restsharp/RestSharp#1482]
I'm getting data=null when trying to use **ExecuteAsync<ProductResponse>** 

This is the code:
![image](https://user-images.githubusercontent.com/13424257/87881336-3ae3b100-ca01-11ea-8c1f-2ec4f37c0e35.png)

And this is the response class:
![image](https://user-images.githubusercontent.com/13424257/87881382-901fc280-ca01-11ea-8cd7-349638fa96be.png)

I'm getting this exception:
System.NullReferenceException
RestSharp.IRestResponse<T>.Data.get returned null.

As you can see here there is Content:
{"success":true,"message":"Succesfully added"}
VS: `{\"success\":true,\"message\":\"Successfully product added.\"}`
"success" is a boolean value and "message" is a string value.

![image](https://user-images.githubusercontent.com/13424257/87882894-13461600-ca0c-11ea-9bda-5edf8507f39f.png)

What am I doning wrong? Why I'm getting data=null?

Thanks.

**Comment by burekas7** [comment]
Ok so this is what solve my issue:
https://github.com/restsharp/RestSharp/issues/868#issuecomment-260670154

But why should I need to add this line while it said that it should do it automatically here:
https://restsharp.dev/getting-started/getting-started.html#content-type

And by the way, is there any difference between using PostAsync or ExecuteAsync?

**Comment by alexeyzimarev** [comment]
`PostAsync` does the `POST` request when `ExecuteAsync` needs a parameter for the request type. It is quite clear from the `PostAsync` code.

> There is no need to set the Content-Type or add the DataFormat parameter to the request when using those methods, RestSharp will do it for you.

We do indeed set the request content type. I am not sure how it contradicts with the fact that you need to change the response content type. Apparently, your server returns the JSON response but doesn't set the content type correctly. That's why you need to set it manually.

The issue arises quite often and I think we can do something about it. There are too many broken servers out there.
