### ISSUE TITLE
Marvin.Json doc not deserializing correctly on API side

### ISSUE THREAD

**Issue by Rab815** [restsharp/RestSharp#1497]
## Expected Behavior
[{"value":83200.00,"path":"/annualsalary","op":"replace"},{"value":true,"path":"/autopay","op":"replace"}]

## Actual Behavior
{=[{"value":80600.0,"path":"/annualsalary","op":"replace"},{"value":true,"path":"/autopay","op":"replace"}]}

## Steps to Reproduce the Problem
- attempted to use built in addjsonbody and whatever updates were made its at it's core it also seems, with the latest version to serialize more correctly with patch docs but it seems to expect that the content will be precursored with an "{application/json=" but doesn't preset the application/json content type

      var response = await _client.ExecuteAsync<AssignmentPayRateV1ResponseModel>(new RestRequest(dataUri, Method.PATCH)
        .AddHeader("content-type", "application/json")
        .AddAuthorization(Identity.Current.Jwt)
        .AddJsonBody(assignmentPayRatePatchDoc));

the following worked:

      var request = new RestRequest(dataUri, Method.PATCH)
        .AddAuthorization(Identity.Current.Jwt)
        .AddParameter("application/json", JsonConvert.SerializeObject(assignmentPayRatePatchDoc), ParameterType.RequestBody);
      var response = await _client.ExecuteAsync<AssignmentPayRateV1ResponseModel>(request);

The only way I could the expected behavior to occur is bypassing some automatic functionality and using the above AddParameter method

My guess is the addjsonbody should either set application/json prior to the equals or omit the body curly brackets and equals sign all together
 
## Specifications

  - Version: latest
  - Platform: windows .net 4.5.2
  - Subsystem:

Will not deserialize properly at the api level due to the added {= in the front and } on the backside of the serialized request

**Comment by alexeyzimarev** [comment]
They  d fault JSoN serialiser is *not* NewtonspftJson. It's all detailed in the dark can.

**Comment by Rab815** [comment]
Dark can?  I tried the newest version and it serialized thing better but
wrapped it in an object notation.

**Comment by alexeyzimarev** [comment]
Bloody autocorrect, sorry. I meant ”in the docs”.

**Comment by Rab815** [comment]
ok I just meant that using the addjsonbody, the built in serializer doesnt'
seem to be aware of how to serialize a patch doc.  I was only able to get
it working by using the add parameter function and pre-serializing the
patch doc with newtonsoft.  Is there a way to set NewtonSoft as the default
serializer for a given RestClient, or given RestRequest.  What changes were
made between 105 and version 106 because whatever was done the serializer
in the newer version seems to get the serialization right through the
addisonbody function but seems to concat a {= to the front of the object?

Doug

**Comment by alexeyzimarev** [comment]
RestSharp doesn't seem to have any special code for `PATCH` requests, it uses the same code as for `PUT` and `POST`. So I am genuinely confused about why this happens.

I see that in the first spinnet you use `assignmentPayRateV1RequestMode` and in the second one it's `assignmentPayRatePatchDoc`. Is it the same contract? What is the contract code?

**Comment by Rab815** [comment]
sorry that was a miss type... it's the patch doc in both cases.  I
corrected it on the issue...  it seems that the version of the simplejson
serializer in RestSharp version 105.2.3 doesn't know how to serialize a
patch doc properly... because in the first example using the addjsonbody,
the request is serialized as such

{"Operations":[{"OperationType":2,"value":83200.00,"path":"/annualsalary","op":"replace","from":null},{"OperationType":2,"value":true,"path":"/autopay","op":"replace","from":null}}

I noticed the code path for addjsonbody automatically serializes the
request for you using the built in serializer.

in the second when I use newtonsoft prior to the send and use addparamter...
[{"value":83200.00,"path":"/annualsalary","op":"replace"},{"value":true,"path":"/autopay","op":"replace"}]

now when I upgraded to the newest version 106.11.4 of your RestSharp
client... using the first example again.. using the addjsonbody
*{=*
[{"value":80600.0,"path":"/annualsalary","op":"replace"},{"value":true,"path":"/autopay","op":"replace"}
*}*

Notice the highlighted red portion... my assumption was you went to using
newtonsoft, however that was a poor assumption so my next assumption is
somewhere between 105.2.3 and 106.11.4 you upgraded the simple json
parser... perhaps the newer version of simplejson, if that's what you did
knows know about how to serialize patch docs.

Let me know if any of this makes sense...

Doug

**Comment by alexeyzimarev** [comment]
That's right, I got a more recent version of SimpleJson in some time ago, but all the tests were green.

It would really help if you can post the request class code.

**Comment by Rab815** [comment]
this should get ya what you need I had to make the classes smaller and
change some names

Request Model

public class RequestModel
{
    public decimal? AnnualSalary { get; set; }
    public bool AutoPay { get; set; }

public JsonPatchDocument<RequestModel> ToRequestModelPatchDoc()
    {
 // JsonPatchDocument is Marvin.Json
      var newPatchDoc = new JsonPatchDocument<RequestModel>();
      newPatchDoc.Replace(x => x.AnnualSalary, AnnualSalary);
      newPatchDoc.Replace(x => x.AutoPay, AutoPay);
 return newPatchDoc;
    }
 }

This is the code in the request function this DID NOT work
    public async Task<ResponseModel> EditEmployeePayRate(RequestModel
requestModel)
    {
      var dataUri = $"/test/dataurl";
      var requestModelPatchDoc = requestModel.ToRequestModelPatchDoc();
      var request = new RestRequest(dataUri, Method.PATCH)
        .AddHeader("content-type", "application/json")
        .AddAuthorization(Identity.Current.Jwt)
        .AddJsonBody(requestModelPatchDoc))
      var response = await _client.ExecuteAsync<ResponseModel>(request);
}

This is the code in the request function this worked
    public async Task<ResponseModel> EditEmployeePayRate(RequestModel
requestModel)
    {
      var dataUri = $"/test/dataurl";
      var requestModelPatchDoc = requestModel.ToRequestModelPatchDoc();
      var request = new RestRequest(dataUri, Method.PATCH)
        .AddAuthorization(Identity.Current.Jwt)
        .AddParameter("application/json",
JsonConvert.SerializeObject(requestModelPatchDoc),
ParameterType.RequestBody);
      var response = await _client.ExecuteAsync<ResponseModel>(request);
}

Api Code accepting the request

[HttpPatch] // Patch Verb
    public async Task<bool>
TestApi([FromBody]JsonPatchDocument<AssignmentPayRateV1Model> patchDoc)
    {
      var response = await
_rateManager.UpdateAssignmentPayRateAsync(companyId, assignmentId,
patchDoc, payRateId);
      return response;
    }

Marvin.Json.Patch is version 2.1.1.0
RestSharp Version was 105.2.3
Even after upgrading RestSharp to verion 106.11.4 it was close on the
serialization but not quite right going through addJsonBody

Doug

**Comment by alexeyzimarev** [comment]
Why do you need to use the patch doc? Is it because you might send not all the fields so you want to prevent updates to `null` values?

**Comment by Rab815** [comment]
Its part of the rest standard and required by various teams within the org.

**Comment by nesc58** [comment]
Maybe I found something interesting.
Serialization with SimpleJson will serialize all existing properties. So, `JsonPatchDocument<RequestModel>` contains Operations, ContractResolver, CaseTransformType and so on. I have create tests and the json produced by SimpleJson looks like: `{"Operations":[{"OperationType":2,"value":83200.00,"path":"/annualsalary","op":"replace","from":null},{"OperationType":2,"value":true,"path":"/autopay","op":"replace","from":null}}`
For me this seems correct. To use a custom serialization, I would suggest using a custom serializer.

Marvin.JsonPatch is some kind of extension for NewtonSoft.Json. The serialization of `JsonPatchDocument<TModel>` is done by a specified JsonConvert attribute: https://github.com/KevinDockx/JsonPatch/blob/master/src/Marvin.JsonPatch/JsonPatchDocumentOfT.cs#L26
The converter is here: https://github.com/KevinDockx/JsonPatch/blob/master/src/Marvin.JsonPatch/Converters/TypedJsonPatchDocumentConverter.cs

SimpleJson does not support these attributes.

```
    _restClient.UseSerializer(() => new NewtonSoftJsonSerializer());
```

And here is the class
```
class NewtonSoftJsonSerializer : IRestSerializer
    {
        private static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            DefaultValueHandling = DefaultValueHandling.Ignore
        };

        public string Serialize(object obj) =>
            JsonConvert.SerializeObject(obj, Settings);

        public string Serialize(Parameter parameter) =>
            JsonConvert.SerializeObject(parameter.Value, Settings);

        public T Deserialize<T>(IRestResponse response)
        {
            return JsonConvert.DeserializeObject<T>(response.Content, Settings);
        }

        public string[] SupportedContentTypes { get; } =
        {
            "application/json", "text/json", "text/x-json", "text/javascript", "*+json"
        };

        public string ContentType { get; set; } = "application/json";

        public DataFormat DataFormat { get; } = DataFormat.Json;
    }
```

Using the simple `RestSharp.Serializers.NewtonsoftJson` is not working, in cause of dependency conflicts. Marvin.Json uses an older version of `NewtonSoft.Json` than `RestSharp.Serializers.NewtonsoftJson`

With the configuration above (UseSerializer()) I can use the following code: 
```
    var dataUri = $"/test/dataurl";
    var requestModelPatchDoc = requestModel.ToRequestModelPatchDoc();
    var request = new RestRequest(dataUri, Method.PATCH)
        .AddHeader("content-type", "application/json")
        .AddJsonBody(requestModelPatchDoc);
```
The `Body` the server received is: `[{"value":83200.0,"path":"/annualsalary","op":"replace"},{"value":true,"path":"/autopay","op":"replace"}]`



I would say: Changing the serializer to NewtonSoft.Json will solve the problem. It is not the problem of SimpleJson because `JsonPatchDocument<TModel>` uses a NewtonSoft.Json specific attribute to serialize the class to `[{"value":83200.0,"path":"/annualsalary","op":"replace"},{"value":true,"path":"/autopay","op":"replace"}]` instead of a simple property-based serialization like: `{"Operations":[{"OperationType":2,"value":83200.00,"path":"/annualsalary","op":"replace","from":null},{"OperationType":2,"value":true,"path":"/autopay","op":"replace","from":null}}`


Does this helps?

**Comment by alexeyzimarev** [comment]
Good analysis @nesc58, I appreciate it.

I am only concerned about the fact that the older version of RestSharp worked. I cannot confirm that since I also have a feeling that it is specific to that particular Marvin.Json thing, but I wanted to double-check.

**Comment by Rab815** [comment]
It was the newer version of RestSharp that had the patch document
serialized closer to what it should be, it was just that using the
addJsonBody method wrapped the patch doc in {= ... } that was the issue.
The patch doc would deserialize correctly with that body tags wrapping in
with the equal sign in front of it... I think if it was {applciation/json=
... } then it would be ok. or just the body of the patch doc itself without
the application/json precursor since it would be a header.

**Comment by Rab815** [comment]
The version of RestSharp we are currently using does not have the method
UserSerializer() on it which is why I couldn't use it...

I ended up using

      var dataUri =
$"corehr/v1/companies/{companyId}/assignments/{assignmentId}/payrates/{payRateId}";
      var assignmentPayRatePatchDoc =
assignmentPayRateV1RequestModel.ToAssignmentPayRatePatchDoc();
      var request = new RestRequest(dataUri, Method.PATCH)
        .AddAuthorization(Identity.Current.Jwt)
        .AddParameter("application/json",
*JsonConvert.SerializeObject(assignmentPayRatePatchDoc)*,
ParameterType.RequestBody);
      var response = await
_client.ExecuteAsync<AssignmentPayRateV1ResponseModel>(request);

The bolded type is NewtonSoft.Json.  Perhaps when we upgrade to the newest
RestSharp client we can use the approach you stated.  Your explanation does
help.  I'm assuming the newest version of RestSharp has the
UserSerializer() method on it?

Doug

**Comment by nesc58** [comment]
Yes, _UseSerializer()_ not exists for RestSharp 105.x.
Creating the body without any help methods like (AddJsonBody) will work. 
But I ask myself why this has been working with older versions. For me the _Actual Behavior_ is not reproducible. I am unable to reproduce a string like the given in _Actual Behavior_.

I have tested a lot of version combinations but no one works for me. All versions I have tested are creating json strings like  `{"Operations":[{"OperationType":2,"value":83200.00,"path":"/annualsalary","op":"replace","from":null},{"OperationType":2,"value":true,"path":"/autopay","op":"replace","from":null}}` 

I have no idea why this has been working for the past days.

Here is my solution to use NewtonSoft.Json with RestSharp 105.x.

I have created a class which implements IDeserializer and ISerializer. I have added a method which will register the SupportedContentTypes as handler _Register(IRestClient ...)_

My serializer looks like
```
public class NewtonsoftJsonDeserializer : IDeserializer, ISerializer
{
	private static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
	{
		NullValueHandling = NullValueHandling.Ignore,
		DefaultValueHandling = DefaultValueHandling.Ignore
	};

	public T Deserialize<T>(IRestResponse response) => JsonConvert.DeserializeObject<T>(response.Content, Settings);
	public string Serialize(object obj) => JsonConvert.SerializeObject(obj, Settings);

	public string RootElement { get; set; }
	public string Namespace { get; set; }
	public string DateFormat { get; set; }
	public string ContentType { get; set; } = "application/json";

	private string[] SupportedContentTypes { get; } =
	{
		"application/json", "text/json", "text/x-json", "text/javascript", "*+json"
	};

	public void Register(IRestClient restClient)
	{
		foreach (var contentType in SupportedContentTypes)
		{
			restClient.AddHandler(contentType, this);
		}
	}
}
```

To deserialize with the created NewtonsonSerrializer we must add the serialzier as handler
```
_restClient = new RestClient("http://localhost:8080")
{
    Encoding = Encoding.UTF8,
    UseSynchronizationContext = false
};
_jsonSerializer= new NewtonsoftJsonDeserializer();
_jsonSerializer.Register(_restClient);
```

To use AddJsonBody method we have to set _JsonSerializer_ property to the newtonsoft serializer. Otherwise SimpleJson will be used.
```
var dataUri = $"/test/dataurl";
var requestModel = new RequestModel {AnnualSalary = 83200, AutoPay = true};
var requestModelPatchDoc = requestModel.ToRequestModelPatchDoc();
var request = new RestRequest(dataUri, Method.PATCH) {JsonSerializer = _jsonSerializer}
    .AddJsonBody(requestModelPatchDoc);
var response = _restClient.Execute(request);
```

Now the body looks like `[{"value":83200.0,"path":"/annualsalary","op":"replace"},{"value":true,"path":"/autopay","op":"replace"}]`.

This code is on client side. The server backend must use newtonsoft json to deserialize this json string. Otherwise the backend is not able to deserialize this string into the correct model. All properties will be empty, when the server is unable to deserialize.

**Comment by Rab815** [comment]
Thanks I'll try this solution out...

Doug

**Comment by alexeyzimarev** [comment]
Ok, thanks again @nesc58 for the analysis and the suggestion.

I agree that Mavin.Json being a derivative/addon of an older version of NewtonsoftJson gives us no chance to support it with SimpleJson. Custom serialiser is the best way to go.
