### ISSUE TITLE
RestClient.AddDefaultParameter: The default parameter doesn't show up in request

### ISSUE THREAD

**Issue by ns6000** [restsharp/RestSharp#1544]
This is possibly the same issue as https://github.com/restsharp/RestSharp/issues/1249

I'm experiencing this problem after upgrading my project from .NET Core 2.0 to .NET Core 3.0 and subsequently from RestSharp 106.3.1 to 106.11.7, it used to function fine before the upgrade.

## Expected Behavior
After the call to RestClient method AddDefaultParameter(...) every request using this client should add those parameters.

## Actual Behavior
Requests (GET or POST) do not contains those parameters.

## Steps to Reproduce the Problem
  1. create RestClient instance client
  2. client.AddDefaultParameter("x-custom-param", "test");
  3. (if you break here, you can see in Watch that client.DefaultParameters collection really contains custom parameter)
  4. create RestRequest instance req
  5. (in Watch: request.Parameters has no custom parameters which is probably fine because it still has no connection to client yet)
  6. await client.ExecutePostAsync<ModelClass>(request); (or ExecuteGetAsync)
  7. (in Watch: request.Parameters still does not contains custom parameters)

## Specifications

  - Version: 106.11.7
  - Platform: Win10
  - Subsystem: .NET Core 3.0

**Comment by alexeyzimarev** [comment]
Checking the request doesn't confirm that those parameters aren't sent to the target endpoint as the request itself supposes to be immutable. We do not add default parameters to the request instance, they are, however, sent in the request.

It would be nice if you verify if the destination server does not receive those parameters, which I can hardly believe since default parameters are covered by tests and none of them fail.

**Comment by ns6000** [comment]
Oh, ok, i'll check the other side then, thanks!

**Comment by ns6000** [comment]
Ok, my bad, i can confirm default parameters are successfully sent with requests.
