### ISSUE TITLE
Uploading big sized files 

### ISSUE THREAD

**Issue by gorkemhacioglu** [restsharp/RestSharp#1573]
Hi,

I am trying to upload a .zip file which is ~700MB. I can upload small sized files without any problem. But when i try to upload big size file, I don't see any file on my request at server side. What am I doing wrong? Here is my code;

        
            var request = new RestRequest(ExportFilePath, Method.POST);

            request.AddParameter("scanId", result.Id, ParameterType.QueryString);

            try
            {
                var f = new FileInfo(zippedFilePath);
                var fileLength = f.Length;

                var fileParameter = new FileParameter
                {
                    Name = Path.GetFileName(zippedFilePath),
                    FileName = Path.GetFileName(zippedFilePath),
                    ContentLength = fileLength,
                    Writer = s =>
                    {
                        using var file = new StreamReader(new FileStream(zippedFilePath, FileMode.Open, FileAccess.Read));
                        file.BaseStream.CopyTo(s);
                    },
                    ContentType = "application/zip"
                };

                request.AddFile(fileParameter.Name, fileParameter.Writer, fileParameter.FileName, fileParameter.ContentLength, fileParameter.ContentType);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            var importFileResponse = await _restClient.ExecutePostAsync(request, cancellationToken);

            switch (importFileResponse.StatusCode)
            {
                case HttpStatusCode.OK:
                    return new CloudApiResultBase
                    {
                        HasError = false,
                        ExportedScanId = result.Id,
                    };
                case HttpStatusCode.BadRequest:
                    return new CloudApiResultBase
                    {
                        HasError = true,
                        ErrorMessage = Literals.CloudManager_FileExists,
                    };
                default:
                    return ServerFailure(importFileResponse);
            }

## Specifications

  - Version: 106.10.1.0
  - Platform: Windows 10

**Comment by Don-didi** [comment]
Hi,

I'm encountering similar behaviour when trying to upload .zip files that are bigger then 1GB using the example below:
```
        private void PutBigZip(string Location, string FilePath)
        {
            string Name = Path.GetFileName(FilePath);
            var request = new RestRequest("$"files?location={Location}", Method.PUT);
            request.AddHeader("accept", "application/json");
            request.AddHeader("Content-Type", "multipart/form-data");

            string contentType = "application/x-zip-compressed";
            FileStream fileStream = new FileStream(FilePath, FileMode.Open, FileAccess.Read);
            request.AddFile("631MB.zip", stream => fileStream.CopyTo(stream), Name, fileStream.Length, contentType);
            request.Timeout = 120*60000;

            var response =  _restClient.Execute(request);
            fileStream.Close();
        }
```
Probably i'm doing something wrong or i'm missing a setting because it works fine for files less then 1GB.
I've noticed when viewing the Process Memory displayed in the Diagnostic Tool of VS that the memory usage is around 700MB when i send a file of 631MB in size.
![afbeelding](https://user-images.githubusercontent.com/86706768/123915116-71031200-d980-11eb-8180-8017259ddb19.png)
When sending a 947MB file, a little less then 1Gb is allocated.
![afbeelding](https://user-images.githubusercontent.com/86706768/123915608-fbe40c80-d980-11eb-9f69-425db5453339.png)
When sending a 1.23GB file the memory usage drops to 35MB and a timeout is raised (in this example after 2 hours).
![afbeelding](https://user-images.githubusercontent.com/86706768/123917093-b1fc2600-d982-11eb-900c-779274b97a1a.png)
I don't know if this could be related to why it appears that the file is not transferred? (e.g. it's send the file in smaller packets which in the end takes a long time to transfer)
