### ISSUE TITLE
IRestClient interface

### ISSUE THREAD

**Issue by alexeyzimarev** [restsharp/RestSharp#1696]
Version 107 got several interfaces removed, which is one of the major breaking changes in that version.

It seems most of the interfaces were okay to remove, except `IRestClient`. My arguments are [described](https://restsharp.dev/v107/#motivation) in the docs.

This issue is a place where we should have a civilised discussion about it. I will not follow up on the interface issue anywhere else, except here.

Some details about the current state of the `RestClient` API signature.
- All the sync methods were removed. Those who need it can make extensions, wrapping up async calls in some [async helper](https://github.com/rebus-org/Rebus/blob/master/Rebus/Bus/Advanced/AsyncHelpers.cs).
- Most of the overloads for making requests are now extensions, as they just call each other, so they would never be part of any interface anyway.
- Most of the options that were previously on `IRestClient` and `IRestRequest` are now in `RestClientOptions`, which is a property bag and, therefore, won't have any interface

So, what's there in stock for `IRestClient`? Basically, it boils down to this signature:

```csharp
namespace RestSharp; 

public interface IRestClient {
    RestClient AddDefaultParameter(Parameter parameter);

    Task<RestResponse> ExecuteAsync(RestRequest request, CancellationToken cancellationToken = default);
}

```

The question now is if it makes sense to introduce an interface with those two functions? Please comment.

**Comment by astrohart** [comment]
I would think it would, in order to maintain SOLID code.  Also, as several other people pointed out previously, we are not always immune to managers etc. making us code to interfaces, do gratuitous TDD and automated-unit-test writing etc/mocking, and/or use IoC containers.  Bosses like to make software engineers do things "because I heard about it at a conference," or "the insurance is making us," etc.

**Comment by alexeyzimarev** [comment]
Brian, I understand the argument about managers, although in my 30 years of engineering I never encountered a single manager who was telling me how to write code... I mean, if you write your code against an interface it's one thing. But how some managers can tell a third-party library how to write _their_ code? `HttpClient` doesn't have any interfaces implemented and it seems to be fine, no?

Automated testing and mocking HTTP requests are totally possible with RestSharp in its current shape. I have shown an option in the docs.

I see no issues with using DI containers as well, as `HttpClient` does with its nice extensions. In fact, I plan to add some DI support to make it easier and push people to use RestSharp properly (typed clients, etc).

The SOLID argument is not solid :) What do you mean by that, could you elaborate?

Then again, I am seriously not against adding that small interface. However, I would not be happy to add `IRestRequest` and `IRestResponse` back as those are glorified property bags.

**Comment by fjmorel** [comment]
A typical method in a wrapper service for my HTTP calls does the following
1. Take some inputs to form a request
2. Execute
3. Handle response (maybe retry, return data)

If I can mock `IRestClient`, then I can verify the contents of the `RestRequest` given to it by my method. That lets me avoid splitting 1 into a separate method just for testing that I correctly crafted the web request (which I want because string formatting is tricky).

If I can mock `IRestClient`, then I can setup responses for 200, 404, 401, etc and don't need to split out 3 either.

Each method is already short enough that I _don't want_ to split it up just for test coverage. Example:

```csharp
public async Task<List<Something>> GetData(DateTimeOffset startEpoch, DateTimeOffset endEpoch)
{
    var request = new RestRequest("/url", Method.GET);
    await AddBearerToken(request);// other method which might make a request to authenticate or use cached token
    request.AddQueryParameter("start", startEpoch.ToUnixTimeSeconds().ToString());
    request.AddQueryParameter("end", endEpoch.ToUnixTimeSeconds().ToString());

    var result = await _client.ExecuteAsync<ApiResponseModel>(request);
    if (result.StatusCode != HttpStatusCode.OK)
        throw new Exception($"Failed to fetch data. Status code: \"{(int)result.StatusCode}\", message: \"{result.StatusDescription}\"");

    return result.Data.ThingICareAbout;
}
```

**Comment by alexeyzimarev** [comment]
@fjmorel what of that is not possible to do with [MockHttp](https://github.com/richardszalay/mockhttp)? It gives you even better options to ensure the request comes in the correct format and has the correct content type, authorisation headers, etc.

**Comment by danielwagn3r** [comment]
> I see no issues with using DI containers as well, as `HttpClient` does with its nice extensions. In fact, I plan to add some DI support to make it easier and push people to use RestSharp properly (typed clients, etc).

Can you tell a little bit more about your plans on DI support? Perhaps a word on DI in the docs could clarify many questions before the've to be asked.

**Comment by alexeyzimarev** [comment]
The DI registration heavily depends if you want to follow the same pattern as Microsoft does, using `IHttpClientFactory`, registering the client as a transient dependency.

For many use cases it's enough to register a typed client as a singleton:

```csharp
services.AddSingleton<IMyApiClient>(new MyApiClient(new RestClient(options)));
```

If I'd to provide some use of `IHttpClientFactory` registration extensions, I'd need to know if people want to configure the `HttpClient` instance used by `RestClient` on the outside. In this case, lots of options that RestSharp uses to configure the message handler won't be applicable.

**Comment by fjmorel** [comment]
> @fjmorel what of that is not possible to do with [MockHttp](https://github.com/richardszalay/mockhttp)? It gives you even better options to ensure the request comes in the correct format and has the correct content type, authorisation headers, etc.

Thanks! I didn't know about that library. I've been using [Moq.Contrib.HttpClient](https://github.com/maxkagamine/Moq.Contrib.HttpClient) in places we used HttpClient rather than RestSharp.

This library using HttpClient is an implementation detail that I don't think library users should have to think about, unless they have specific requirements making the need for a custom HttpClient necessary. Having the interface makes testing easier for all users without having to add extra dependencies.

**Comment by alexeyzimarev** [comment]
The library you mentioned would work as well. As long as you can add a delegating handler, it will be possible to test RestSharp calls. All you need to do is to compose or override the message handler used by the wrapped HttpClient:

```csharp
var client = new RestClient(...) { ConfigureMessageHandler = _ => mockedHandler };
```

**Comment by sspates-starbucks** [comment]
This is not necessary if the existing RestClient methods are marked virtual.  This will allow for mocking overrides of the public methods instead of needing a full interface. 

One of the two is necessary as the handler system is not able to simulate invalid http responses.  We switched from Http client to RestSharp because RestSharp had an interface that allowed us to simulate the result of those responses as well as other error conditions not simulatable through the mock handler.   Some of these result in StatusCode 0 or exceptions being thrown which require an interface or virtual method.

**Comment by alexeyzimarev** [comment]
@sspates-starbucks why can't you simulate the error response with a testing handler like `MockHttp`? It provides a behaviour that is much closer to reality. It can return anything you want based on its configuration.

**Comment by alexeyzimarev** [comment]
@maor-rosenfeld thanks for your extensive and elaborative feedback for this issue.

**Comment by alexeyzimarev** [comment]
If we keep discussing testing, maybe it's a good idea to post some test samples and check how these tests can be refactored. So far, the discussion goes quite theoretical imo.

**Comment by maor-rosenfeld** [comment]
@alexeyzimarev we can argue all day about use cases of using the interface for tests, extension methods, tests on these extension methods and other reasons of why suddenly removing all interface from an existing infrastructure package is a bad idea, but at this point it's clear that you're here to tell us how to write code. 

I'm sorry if I choose not to align with your views, but at this point upgrading to the latest version of RestSharp is so painful that there's really no justification to even try. 

On a positive note, I'm completely with you regarding the separation of services and settings objects. I like `RestClientOptions`.

**Comment by alexeyzimarev** [comment]
@maor-rosenfeld you definitely know how to motivate OSS maintainers to keep doing their community work for free.

**Comment by lukos** [comment]
I've come here from a breaking scenario that I'm not sure I can fix other than backing out the upgrade to 107 due to missing IRestClient.

I updated one of my libraries to use 107. Why not right? I'm trying to be proactive with keeping libs up to date. It all seemed to work OK until some tests starting failing. This is because we use a third-party library and they reference IRestClient and v106 of the library. I could ask them to update but I don't see that they would prioritise that and it would then force all of their customers to update to v107 as well which might be a big deal. If I use an assembly redirect to 107, it won't work because it won't find IRestClient and if I use 106, my code won't work because the method signatures changed.

I'm not sure what I would have done differently but perhaps something as simple a a different nuget package with different namespaces and mark the old one as deprecated. Then we can run them side-by-side until everyone is on 107?

Not sure. Any suggestions?

**Comment by alexeyzimarev** [comment]
@lukos I don't think it would work in any scenario, interfaces or not. RestSharp v107 internals are completely different due to migration to `HttpClient` and ditching `HttpWebRequest`. It made it impossible to keep the API backwards compatible, and even with interfaces, the API scope of those interfaces won't ever be compatible. Lots of properties of `RestClient` and `RestRequest` are moved to `RestClientOptions` and there's no way to keep them where those properties were before.

**Comment by sspates-starbucks** [comment]
We are running into cases now where one library requires the interface and another requires the v107 structure, we can't upgrade either one due to the lack of backwards compatibility with IRestClient.   Adding a compatibility wrapper that implement the interfaces might be a way to handle this better rather than implementing the interface on the current client.

**Comment by alexeyzimarev** [comment]
@sspates-starbucks Even if there's something to make things build-time compatible, these won't be compatible at runtime anyway. As I mentioned, most of the properties of those (`IRestClient` and `IRestRequest`) interfaces were (by necessity) moved to `RestClientOptions`, and it's something that simply cannot be undone due to the configuration of `HttpMessageHandler`.

I can only suggest opening issues for those libraries that still use RestSharp 106 and helping them with the migration. It's not a lot of work honestly.

**Comment by Terebi42** [comment]
The new class having internal only options generates problems for dependency injection. I set up my DI container to hand out RestClient, but different consumers need different options. There is now now way to set the options after having an instantiated Client.

**Comment by alexeyzimarev** [comment]
@Terebi42 that's why I advocate wrapping `RestClient` in a particular API client, so you can wire it like this:

```csharp
services.AddSingleton<ITwitterClient>(new TwitterClient(new RestClient(twitterOptions)));
```

But I plan to address it better, just haven't found a good way to do it yet. Either I will make some extensions for `IHttpClientFactory` or make a new factory with named registrations for options.

**Comment by alexsaare** [comment]
Every man and his dog has an opinion on software design/standards and the debates will rage on forever - they're usually just different mindsets/approaches.  Those mindsets aren't even usually the mindset of the developer using your library, they're probably dictated by the organisation they work for and having a conversation to change those standards is either way above their pay grade or a battle that's not worth fighting.  

The problem here isn't one of who is right or wrong, it's one of practicality.  The removal of the interfaces causes the amount of work some consumers has to do to significantly increase.  Most devs really just need to deliver the work they had promised to within the timeframe promised.   I'm a huge fan of MockHttp but in my case updating over 1000 tests to use it which were written 5 years ago is a huge amount of work.  No matter how you plan your pipeline, the sizing of the work item is now completely invalid.  The amount of work required to update your library has become inhibitive to doing so - it will either have to be picked up as a separate work item or it just won't ever get updated.

Irrespective of whether consumers are testing the right thing, using IoC correctly or just plain writing crap code, they no longer have the flexibility to choose like they used to.  I think most devs would agree that the code changes make sense but at the end of the day we all need to deliver functionality to a business and I guarantee that those business users really don't care how well the code is written as long as it reliably does what they need. 

The best development tools out there make our lives easier.  That's why we use them - they abstract us away from the detail/hard work we really don't need to care about and they provide flexibility to customise how we utilise them.  They help us do more, faster.  Removing these interfaces does the opposite of that, irrespective of whether it's a "better" code or not.

**Comment by lukos** [comment]
What everyone is saying is correct. Of course, we appreciate Alexey for making this library but the changes are very breaking.

It seems like the best way out of it would be to create a separate library with a different name/package name (and importantly, different namespaces) to contain your newer/better way of doing things and which should be used by people going forwards. Any serious bugs found in the old library will probably be fixed but otherwise it won't get any new features.

This way, we can have both packages alongside each other so if we can update our own code for the new library we can do that without forcing all of our dependencies to update all of their code at the same time. If they eventually do, then we can eventually uninstal the old package.

Not sure if you think that sounds fair or not?

**Comment by alexeyzimarev** [comment]
The question is why is there such a strong need to migrate to v107 if v106 works fine for most? Migration to `HttpClient` is a big change in itself, the `IRestRequest` (for example) is impossible to shape to the same form as it was before anyway, as well as `IRestClient` interface API surface cannot be recovered.

**Comment by alexsaare** [comment]
Why update?  People want the [stated benefits](https://restsharp.dev/v107/#presumably-solved-issues) that this update (_and future updates_) will bring.  

As a consumer, I shouldn't have to care what implementations are used internally as long as it works.   This is a debate about the impact of the removal of interfaces and the consequences that has for those who use the library.  (The fact that I'm even aware of what components are used internally screams leaky abstraction to me but that's just my opinion and somewhat off topic)

Changing the method signatures is something that's not overly complex to deal with (the compiler will help identify what needs changing and, in our case, this library is abstracted away from our code anyway) however, removing all the interfaces entirely fundamentally changes how to set up and work with the library and how easy/difficult that is given what's gone before. 

The work you've done is great - we're just providing feedback of the real world issues it causing us.  Rightly or wrongly, people consume this library is a myriad of ways and for us, the migration path is so large that it's currently a barrier to entry.

**Comment by alexsaare** [comment]
So this is very specific to our use case but perhaps you'll find it useful....

The interface you defined at the top is perfectly adequate for us.  It doesn't need to maintain the same entire interface.  

You said 

> The question now is if it makes sense to introduce an interface with those two functions?

For us, yes it does.

The classes just need an interface so that all the existing tests remain (mostly) unchanged.

If the classes don't have an interface as described above, we can't mock it **the way we have been doing** or not **_without significant effort_**.  We really don't want to have to _significantly_ change 1000s of tests that were written 5 years ago by someone else.  99% of them simply mock the `Execute` method but they do cover a huge number of scenarios. 

That interface would save us days of effort which we probably won't be able to get resource to schedule at any other time.

**Comment by alexeyzimarev** [comment]
As I mentioned before, I am trying to understand how people use interfaces in tests. Tests aren't PI, nor IP. Please, share your tests.

**Comment by Terebi42** [comment]
To answer some questions @alexeyzimarev posed above : 

1) Why upgrade if we don't need to? Because corporate policy requires us to be on recent versions
2) Though I personally agree with some of your motivations and reasoning regarding testing and interfaces, corporate policy also often doesn't care if a test provides value or not

But my biggest problem is the change to DI because of options. I have an app that connects to 10 different services. Currently I have them all getting an IRestClient via DI, set the options they need in their consumer's constructors, and move on.

You are asking me to create 10 new interfaces, move all that rest configuration logic into the DI configuration, change the signature of every consumer of the rest client etc.  Further, if two services can currently share configuration they can share the injected interface. But if one of them needs a different bit of configuration in the future, now I have to create a new interface for that DI again, and change the signatures again, just to have a different timeout or base url.

**Comment by alexeyzimarev** [comment]
@Terebi42 the DI concern should be fixed differently. I will provide a way to do it at some point, similar to how you'd do it with `HttpClient`. The issue with registering a single dependency as `IRestClient` as it won't work anyway if the client options need to be configured. As many options moved from the request to the client itself, it won't work.

**Comment by alexeyzimarev** [comment]
@Terebi42 as per the latest version requirement, I don't think it is even feasible, although I am not aware of your particular case. Say, you have .NET 6 released in November, does the policy mean you have to upgrade all your applications to .NET 6, with all the breaking changes fixed? I never had such experience in any company.

**Comment by alexeyzimarev** [comment]
Because those options are configuring `HttpMessageHandler`, which is wrapped inside `RestClient`. Changing those options would require creating a new `HttpMessageHandler` instance, and it will make `RestClient` not thread-safe.

**Comment by Terebi42** [comment]
> Because those options are configuring `HttpMessageHandler`, which is wrapped inside `RestClient`. Changing those options would require creating a new `HttpMessageHandler` instance, and it will make `RestClient` not thread-safe.

hrm, well, at least I understand.  Perhaps Ill make a restclient factory that I DI, and pass it options to get the old pattern back

**Comment by alexeyzimarev** [comment]
@Terebi42 I opened an issue for that https://github.com/restsharp/RestSharp/issues/1791

**Comment by kendallb** [comment]
BTW, if you did bring back IRestClient, the only function that matters is all variations of ExecuteAsync(). There are good valid reasons to want to mock ExecuteAsync() to avoid an actual call as its high level enough to mock away a significant amount of lower level stuff. But it's also low level enough that I usually don't bother ;). Usually we mock at the level above that, which is our REST API client contract. After all the point of mocking is to be able to stub out lower level stuff as a black box and assume that black box works correctly. That assumption works as then you expect something else to validate that the actual client itself is properly tested (integration test etc).

And there is a good argument to be had that writing tests to ensure the client itself is actually working correctly is much better being done by mocking HttpClient as suggested. Something that was almost impossible to do with earlier versions of RestSharp, but is now much easier to do now it relies on HttpClient internally so you can swap it out for mocking purposes.

**Comment by kendallb** [comment]
I believe that works because it uses a separate task, so it's a similar pattern achieved in a different way to how Rebus did it. I am not sure which one is more efficient. We use Rebus in our code and I stole their code to solve the deadlock issues when we had it, and it worked. I have also solved in the past simply by running the code in a separate background thread similar to the AspNet approach and that works also. But I think it's higher overhead than the approach taken by Rebus and other libraries?

I am sure either approach works, but I know that just using GetAwaiter().GetResult() on an async function will cause deadlocks in web apps (or Windows Forms apps). We had tons of hung web requests when I was doing it without the task wrapper.

**Comment by alexeyzimarev** [comment]
Updated

**Comment by kendallb** [comment]
Been a while since I looked and and debugged the Rebus version, but I did step through it with a debugger to understand it back then. I am pretty sure it's much lower overhead as it never triggers a separate background thread, so puts no extra pressure on the thread pool. Rather it swaps out the SynchronizationContext so that when the task returns, it comes back on something other than the original sync context which is where you get the deadlocks.

**Comment by alexeyzimarev** [comment]
I don't think there's an explicit new thread when using the task factory. I think it will use the available IO thread from the pool. Synchronization context, on the other hand, produces some overhead. I believe that doing something like `.ConfigureAwait(false).GetAwaiter().GetResult()` would work, but not in WinForms (for example). I also know that ASP.NET Core behaves differently compared with .NET Framework when it comes to `GetAwaiter().GetResult()`

**Comment by kendallb** [comment]
Yes, its possible it would work differently in ASP.NET Core. Porting our code to that is a massive undertaking which is still a work in progress :( But we also use RestSharp in WinForms apps (EasyPost and ShipEngine) so the AsyncHelper approach is what has worked for us.

I guess the only way to tell would be to benchmark the two approaches and see which is faster.

**Comment by kewur** [comment]
From the explanation page;

> The best way to test HTTP calls is to make some, using the actual service you call. However, you might still want to check if your API client forms requests in a certain way. 

I have to disagree with this. I don't think calling actual services from unit tests is good practice. At that point they're functional tests. 

next line goes into that;

> As RestSharp uses HttpClient internally, it certainly uses HttpMessageHandler. Features like delegating handlers allow you to intersect the request pipeline, inspect the request, and substitute the response. You can do it yourself, or use a library like [MockHttp](https://github.com/richardszalay/mockhttp)

this requires me to actually know how you're making your calls inside your library that you publish to nuget. The main reason people wants to use external libraries is to not be concerned about the internals of that external code. It also assumes I know to use this MockHttp library (had no idea it existed, I didnt need to since I've used RestSharp to handle all "HttpClient" related things so far), with the assumption that, that package will also be maintained properly and will not be making breaking changes.

> Mocking an infrastructure component like RestSharp (or HttpClient) is not the best idea.

This statement is also wrong in my opinion. I think the opposite actually, making us test external library code in our _unit_ tests implicitly makes them not unit tests, because we are always testing more than a small "unit" of code, in addition to our code change, now we're testing your code.

> As RestSharp uses HttpClient internally

What happens when you decide to not use HttpClient, but use "MyGrandmasHttpClient". Do we then have to refactor all of our code bases with the "MockMyGrandmasHttpClient" package?

I am fine with removing every other interface on this package. Except for that single one.

This wouldn't be an issue if we were able to mock classes like Java allows, however removing this 1 single interface with 1 single method causes design issues, as well as wasted hours for millions of developers. 

I would also be skeptical about the suggested "if you don't like 107, just remain on 106" By it's nature, RestSharp deals with connectivity, that increases the chances of 0 day vulnerabilities or other security issues. We won't be able remain on 106 forever, and would be forced off of this package. Which would be a shame because we love RestSharp.

I really appreciate your work on maintaining this package, there is a reason it's one of the most popular packages on .NET. I hope you reconsider this decision.

**Comment by alexeyzimarev** [comment]
> What happens when you decide to not use HttpClient, but use "MyGrandmasHttpClient". Do we then have to refactor all of our code bases with the "MockMyGrandmasHttpClient" package?

That's an exaggeration. RestSharp uses elements of .NET under the hood, and for many years it was `WebRequest`. Then, Microsoft decided to scrap it and re-implemented it using `HttpClient`, causing massive problems. Essentially, RestSharp uses the only way available in core .NET to make HTTP calls, and it's `HttpClient` until Microsoft decides to do something else. All other .NET libs for making HTTP calls like Refit or Flur also use `HttpClient`, and most people use `HttpClient` directly. So, when _that_ changes, all the code for .NET will need to change, which is very unlikely.

> This statement is also wrong in my opinion.

The issue here is that by creating an interface mock you will assert if the client is formed according to your idea of how it should be formed. However, it doesn't guarantee that the actual HTTP request will be valid. That's why `HttpClient` has no interface and cannot be mocked. And that's why people normally use a test version of `HttpMessageHandler` instead, as `HttpClient` itself is just forming a message, but the actual _oevr the wire_ implementation is in the handler. See this [SO question](https://stackoverflow.com/questions/36425008/mocking-httpclient-in-unit-tests).

Again, I am not against bringing the interface back, but it won't be the original interface. Essentially, there are just a handful of core functions of the client itself (`ExecuteAsync` is the main one), all the others are just extensions.

I actually think that the interface would help for building something like a retryable client with Polly, as it could be done in a wrapper using composition.

**Comment by RedVinchenzo** [comment]
Hello dear community,
I'm using RestSharp since some times (7 years more or less), I like it as it do the job.
For a new project, I used it, by reflex, and surprise ! No more interface 😨
I will not discuss with project owner about, it's a good choice or not, I will just write quickly my opinion.
I will give up RestSharp usage, and stop recommand it to team members.
I'm using library to save time, I'm using library as a tool to make my work easier.
Now I'll have to invest time to introduce "tricks" for my unit test ? But why ? 
I choose a tool because it fit to my need, RestSharp doesn't fit anymore.
I'm sure this breaking change is relevant, but not for me.
Most of dev will update lib, keep it in 106 (this proposal is a shame 😅), update their code.
For my part, I choose another tool to save time.

**Comment by alexeyzimarev** [comment]
@RedVinchenzo thank you for your feedback, but I am having a hard time understanding how your comment contributed to the discussion. Keeping the API intact just so people don't need to change their code, hm. I don't remember a single library I used that never changed its API.

Now I see what is going to happen. With .NET you have no choice but to use HttpClient one way or another. Flurl, Refit, or whatever wrapper you use, will either use their own `HttpMessageHandler`, or force you to use the same MockHttp. I am quite puzzled hearing "I will just use HttpClient because RestSharp has no interfaces", I wish someone explains that.

**Comment by tzuge** [comment]
I am starting a new project making use of RestSharp, so more focused on the recommended way to mock / unit test today. It appears the example in the docs might be incorrect.

```csharp
var client = new RestClient(...) { ConfigureMessageHandler = _ => mockHttp };
```
versus
```csharp
var client = new RestClient(new RestClientOptions { ConfigureMessageHandler = _ => mockHttp });
```

From my perspective, I like being able to verify through the request using MockHttp, but would also like `IRestClient` for easier mocking at that level. Having both options is nice, and it doesn't seem onerous for the lib to support it. It sounds like the latest version is a new library from compatibility standpoint, so makes sense that `IRestClient` in this version would be a new interface.

**Comment by richardbuckle** [comment]
Conclusion: stick with RestSharp 106 and evaluate other options. I cannot maintain confidence in a dependency whose maintainer is so cavalier about breaking published API without even a nod to proper semantic versioning.

**Comment by richardbuckle** [comment]
> All the deprecated interfaces had only one implementation in RestSharp, so those interfaces were abstracting nothing. It is now unclear what was the purpose for adding those interfaces initially.

It was to allow you to commit to a published API and a decoupled implementation, and to allow users of RestSharp to *easily* write unit tests that respond with canned data without hitting the filesystem or network interface.

Perhaps you have lost sight of the fact that some of us are writing software that calls servers that, while having a published API, are run by a third party.

**Comment by richardbuckle** [comment]
Here's the point, when a package exposes an interface such as `IRestClient`, it is a commitment to support that interface as stable going forward. 

By publishing that interface, you must expect people to develop code against same interface going forward, especially when writing mocks and stubs so that their unit tests do not hit the filesystem nor the network. 

To advise devs to test against the live endpoints shows a complete and utter failure to understand the purpose of unit testing, which is to test a given code unit against a purely local mock.

**Comment by alexeyzimarev** [comment]
@richardbuckle sorry, who are you again? good bye.

**Comment by alexeyzimarev** [comment]
I reviewed #1952 and have a proposal:

- Rename `ExecuteInternal` to `ExecuteRequestAsync` and make it public
- Rename `InternalResponse` to `HttpResponse` and make it public
- Convert `ExecuteAsync` and `DownloadStreamAsync` to extension methods; both are calling `ExecuteRequestAsync`
- Convert `Execute` and `DownloadStream` sync methods to extension methods
- Add the `IRestClient` interface with only _one_ method: `ExecuteRequestAsync`
- Change all extensions of `RestClient` to `IRestClient`. There will be issues with client members that should be included in the interface, so add those too. `Options` is the property I expect to be there.

This will allow composition. For example, I can add a Polly-based wrapped client to retry particular status codes. Btw, I found that the number of retries in the response `Request` property might not work as intended.

How does that sound?

**Comment by alexeyzimarev** [comment]
Hmm, it doesn't really work well as `Options` become public again... One solution is to make it a record again, with init-only properties, and risk incompatibilities with old SDKs. Not sure what's more important.

**Comment by kendallb** [comment]
Seems reasonable to me, but why would the options need to be part of the IRestClient interface anyway? The way I set it up in my branch where options is private again, I have some properties to get back important stuff like the baseurl etc. Those could be part of the IRestClient interface if needed. But I don't think exposing options is necessary at all in order for someone to mock up IRestClient is it?

**Comment by alexeyzimarev** [comment]
Because lots of extensions need those options. So, it's either to extend the API surface of the interface, which makes little sense or expose a shared options container via the interface.

**Comment by alexeyzimarev** [comment]
I guess I took the wrong approach. The internal execute method should remain internal or private. Both `ExecuteAsync` and `DownloadStreamAsync` should be in the interface as it's the basic public API.

**Comment by alexeyzimarev** [comment]
I appreciate some of the feedback on this issue (not all of it). 

However, I see a lot of negativity and unwillingness to understand that:
- the library needs to move on, and breaking changes are inevitable
- keeping the previous API service was hard to maintain, and I am doing most of the work here (thanks to all the contributors, too) for free, which many participants of this discussion, apparently, fail to appreciate
- the number of aggressive and counterproductive comments here is unacceptable

Therefore:
- the interface will be brought back in v109, but its purpose is not to make mocking easier
- I will open another issue for the new interface
- any attack on the maintainers will not be tolerated. those who do it will be blocked for violation of CoC and contribution guidelines
