### ISSUE TITLE
Errors are throwing even though the docs say they shouldn't

### ISSUE THREAD

**Issue by lukos** [restsharp/RestSharp#1698]
## Expected Behavior
When you call an endpoint that returns an error code, e.g. 400, I should get a response object with IsSuccessful set to false and various pieces of information in it as it explains here: https://restsharp.dev/intro.html#response

"None of `ExecuteAsync` overloads throw if the remote server returns an error. You can inspect the response and find the status code, error message, and, potentially, an exception."

## Actual Behavior

An exception is thrown instead. This is thrown from, in my case, `PostAsync` in class `RestClientExtensions` (https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/RestClientExtensions.cs). All of the methods in that class call ThrowIfError(response), which is the opposite of what the docs say.

## Specifications

  - Version: 107.0.3
  - Platform: Windows 10
  - Subsystem: ??

## StackTrace
<details>

```

RestSharp.RestClientExtensions.ThrowIfError(RestResponse response)
RestSharp.RestClientExtensions.PostAsync(RestClient client, RestRequest request, CancellationToken cancellationToken)
SmartRelay.Dashboard.Services.MessagingCustomerService.Signup(string emailAddress, string password) in MessagingCustomerService.cs

                var response = await restClient.PostAsync(clientRequest);

SmartRelay.Dashboard.Controllers.AccountController.Signup(SignupViewModel model) in AccountController.cs

                await customerService.Signup(model.EmailAddress, model.Password);

Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()

```

</details>

**Comment by lukos** [comment]
After reading it again, it appears to be saying, if you use `ExecuteAsync` specifically, it won't throw. If you use any of the XAsync() methods it will.

Is there a reason for this? This seems an unusual difference between methods that seem identical. Exceptions are quite heavyweight operations for something that is not "exceptional", even if it is an error. Presumably it just provides the ability to have a single catch point for all bad requests/too many requests etc?

**Comment by alexeyzimarev** [comment]
You read it correctly. That's the difference between, for example, `ExecuteGetAsync` and `GetAsync`. I agree that throwing an exception is not as fast as checking the result, but that's what many people prefer. It makes sense in case exceptions aren't frequent, and also aren't expected. I also know that `ExecuteXXXAsync` overloads set is not complete, it's WIP for now. ATM you can easily avoid wrapping your calls in try-catch by using `ExecuteGet/PostAsync` or `ExecuteAsync`. You can see that some people prefer to get an exception by looking at `ThrowOnAnyError`, which was added following such demand.

The reason for generic extensions to throw as it's not possible (with the current signature) to get the response code if the request fails. For example, `System.Text.Json` would return `null` if it fails to deserialize the response content. So, if RestSharp also returns `null` in case of an error, there's no way to understand what the problem is. So, I think that for generic overloads it still makes sense to throw.

I am happy to hear suggestions, as adding more extensions is quite trivial, and I am all pro to build better APIs.

**Comment by RodneyRichardson** [comment]
I like the way it is. Perhaps the documentation can be updated to make it clearer that it applies to ExecuteGetAsync, et. al., not just ExecuteAsync.

**Comment by alexeyzimarev** [comment]
I will add a bit more clarifications to the docs soon.

@lukos I am with you here. But, using `ExecuteGetAsync` instead of `GetAsync` solves it, right?

I would personally prefer to kill some of those functions to make the API surface smaller. But it will be an impactful breaking change, so I would plan it with care. 

I opened an issue to discuss #1704
