### ISSUE TITLE
Reduce the number of client extensions

### ISSUE THREAD

**Issue by alexeyzimarev** [restsharp/RestSharp#1704]
RestSharp now has five different ways to make requests:

- `ExecuteAsync` and `ExecuteAsync<T>` that can execute any request, not throwing by default
- `Execute<Method>Async<T>` (`ExecuteGetAsync<T>`, etc) that execute using a specific method, not throwing by default
- `<Method>Async` (`GetAsync`, etc) that execute using a specific method, throwing by default
- `<Method>Async<T>` (`GetAsync<T>`, etc) that execute using a specific method, throwing by default
- `<Method>JsonAsync<T>` (`GetJsonAsync<T>`, etc) that execute using a specific method, JSON content type and accept by default, throwing by default

It looks a bit too much. Can the number of those functions be reduced?

Thoughts:
- Generic functions like `GetAsync<T>` return a deserializer response. How can they report the status code?
- Should transient failures like timeouts and not accessible remote endpoints, throw?
- When wrapping a call in a retry using, for example, Polly, an exception is the only way to trigger the policy

**Comment by lukos** [comment]
The throw functionality could always be a parameter instead of a different overload, that at least reduces the number of overloads.

Personally, I don't like an http API deciding to throw an exception when the failure is actually an application-layer failure, not an exceptional error imho!

Not sure how to deal with retry policy things, seems like there are better ways to handle this than exceptions, which create a lot of runtime effort to create, when mostly, the information they collect is not used if we are only using them for flow control. If they are async, there might be task-type stuff that could be used, which is more in-keeping with best-practice, I'm afraid I don't know enough to offer an opinion there.

**Comment by alexeyzimarev** [comment]
I found out that Polly can handle results, so it's not really an issue:

```csharp
var policy = Policy<RestResponse>.HandleResult(x => x.StatusCode == HttpStatusCode.BadRequest);
```

**Comment by johnfedak** [comment]
Having ExecuteAsync return status codes and GetAsync throw exceptions seems inconsistent.

**Comment by alexeyzimarev** [comment]
@johnfedak well, that's how the old version was built, I am not planning to revert that.

**Comment by alexeyzimarev** [comment]
I mean, I am open to suggestions.

**Comment by johnfedak** [comment]
I'd vote for making the defaults consistent and having an optional "throw exception" parameter- but I understand the value of not making a breaking change.
