### ISSUE TITLE
AddFile() version 107.1.2-alpha.0.7 not working

### ISSUE THREAD

**Issue by bfcavaco** [restsharp/RestSharp#1715]
**Describe the bug**
"StatusCode: InternalServerError, Content-Type: application/json, Content-Length: 16)"

**To Reproduce**
RestClient client = new(strResource);
RestRequest request = new("", Method.Post);
request.AddParameter("Accept-Encoding", "multipart/form-data", ParameterType.HttpHeader);
request.AddParameter("Authorization", CalibryAuthentication.CalibryToken, ParameterType.HttpHeader);
request.AddFile("file", strFile, "application/pdf");
var restResponse = client.ExecuteAsync(request).Result;

**Expected behavior**
Should return statusCode == "OK"

**Stack trace**
There is not stack trace for this issue, only the return status:
InternalServerError, Content-Type: application/json, Content-Length: 16)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET version 4.8
 - Version: 107.1.2-alpha.0.7

**Additional context**
The bug does not crash the code, only keeps returning the same error.

**Comment by CryptxzzX** [comment]
I'm also having this issue in version 107.1.1

**Comment by alexeyzimarev** [comment]
I commented in another issue where you commented. I am not sure why you are adding the accept encoding header. File uploads work fine.

**Comment by alexeyzimarev** [comment]
> It's not even utilizing the fact I'm using AddFile, my server returns Undefined index from PHP because its not receiving anything at all.

AddFile works. You can debug your request using requestbin.com

**Comment by alexeyzimarev** [comment]
@bfcavaco Trace you request, I am sure it's the parameters you add that break it. You only need AddFile.

**Comment by alexeyzimarev** [comment]
Also, it seems like the server returned you a JSON response, but you never posted it in the issue. The server must be telling you what the issue is.

**Comment by bfcavaco** [comment]
@bfcavaco Trace you request, I am sure it's the parameters you add that break it. You only need AddFile.

I could be that but:
I tried without the accept-enconding parameter but sill when I run the ExecuteAsync it takes over a minute to finish and returns the following: "StatusCode: 0, Content-Type: , Content-Length: )". According to the API documentation the "accept-enconding" was required, at least on version 106 of restSharp.
I thought was something on the server side, but this code works on previous version 106 of restSharp, so I don't know what I'm doing wrong, after updating to version 107.1.1 the file no longer uploads. Not with this code anyway, maybe it's my fault, but I already tried several different approaches and had no success upload files.

**Comment by alexeyzimarev** [comment]
`Accept-Encoding` header is for specifying the encoding accepted by the client for the response. But you are setting it to a value which is not a valid encoding, it's a content type.

Again, you got a JSON response from the server, which probably tells you what is wrong, but you don't expose what the server returned you.

Also, it is always a good idea (and the issue template suggests that) to make test calls to a call tracer like requestbin.com, both with a working request, and a failing request. That way you can easily compare what is the difference between those.

I totally understand your PoV that it used to work, and it doesn't work now. But it is not enough to diagnose the issue. RestSharp v107 doesn't compose requests as the previous version does. It uses content classes derived from `HttpContent` and adds the content to the `HttpRequestMessage`, which is sent to the server by `HttpClient`. And normally it "just works", but there are tons of awkward servers that have weird requirements and fail on legit requests, so without knowing (best) what the server wants or (at least) being able to compare a working request with failing request, the issue is impossible to diagnose.

**Comment by bfcavaco** [comment]
Hi Alexey,

Here is the API documentation for uploading a file:
[image: image.png]
And here are the setting using Postman:
[image: image.png]
Using postman it works, I'm able to upload the file.
So, there must be a parameter I'm using incorrectly on restSharp.

Best Regards,
Bruno Cavaco.

Alexey Zimarev ***@***.***> escreveu no dia sábado,
22/01/2022 à(s) 14:28:

**Comment by alexeyzimarev** [comment]
No images, sorry

**Comment by alexeyzimarev** [comment]
I traced the request using your code, for RS 106.15 and the latest 107 alpha. I expected you to do it, but ok.

Here is the request with RS 106:
![Screenshot 2022-01-22 at 15 35 23](https://user-images.githubusercontent.com/2821205/150643042-42c58981-839d-4d77-a22d-29ce998ca7e7.png)

Here is the same request using RS 107 latest alpha
![Screenshot 2022-01-22 at 15 36 58](https://user-images.githubusercontent.com/2821205/150643053-f8947b6d-4d7a-407f-b02a-0a4fce6b5ec1.png)

Apart from the fact that both requests have the wrong `Accept-Encoding` because you explicitly set it, they look identical. The form boundary looks different, but the form boundary value is a free text according to the standards, so it should work either way.

RS 106 didn't support Brotli, but you can disable it by changing the `AllowedDecompressionMethods`.

**Comment by alexeyzimarev** [comment]
I found that people complain about `HttpClient` with `StreamContent` is using the `filename*=utf-8...` that is a part of some obsolete RFC. I am not familiar with the issue, but I made a small change that overrides the default behaviour. In the `RestSharp.107.1.2-alpha.0.9` you will get the same content disposition as before.

**Comment by bfcavaco** [comment]
Hi,

Using this code: (version 106)

string strResource = AnexoOrdemTrabalhoURL + RefOrdemTrabalho.Replace("/", "%2F") + "/upload";
RestClient client = new(strResource);
RestRequest request = new("", Method.POST);
request.AddHeader("Authorization", CalibryAuthentication.CalibryToken);
request.AddFile("file", strFile, "application/pdf");
var restResponse = client.Execute(request);

I have this: (the file was uploaded)
![image](https://user-images.githubusercontent.com/37348687/150772636-3d39dd73-e45b-4e9a-b7b5-f63765606ee2.png)
![image](https://user-images.githubusercontent.com/37348687/150772763-57f46834-2295-43d8-8d9e-9dfed26d2b14.png)
![image](https://user-images.githubusercontent.com/37348687/150772861-0b7e9818-e503-4620-8bb3-48cb0ce1500b.png)

Then  updated to version 107.1.2-alpha.0.14
and user the same code (just changing the necessary that is required on this version):

string strResource = AnexoOrdemTrabalhoURL + RefOrdemTrabalho.Replace("/", "%2F") + "/upload";
RestClient client = new(strResource);
RestRequest request = new("", Method.Post);
request.AddHeader("Authorization", CalibryAuthentication.CalibryToken);
request.AddFile("file", strFile, "application/pdf");
var restResponse = await client.ExecuteAsync(request);

And got this: (the file was not uploaded)
![image](https://user-images.githubusercontent.com/37348687/150774430-1ed020e6-6cf5-4f06-8396-e2de4507e548.png)
![image](https://user-images.githubusercontent.com/37348687/150774498-f548d82a-f1a2-4755-9184-3fb838fd34b6.png)

I must be doing something wrong, the only response I get from the server is: "StatusCode: InternalServerError, Content-Type: application/json, Content-Length: 16)"

Do I have do add any other parameter or change something in the code in order for it to work on version 107?
I'm sorry but I just can't manage to solve this.

**Comment by alexeyzimarev** [comment]
You say the file is not uploaded, but what's there?
![Screenshot 2022-01-24 at 12 33 43](https://user-images.githubusercontent.com/2821205/150775794-ffa82b9d-ba92-4a8f-8bc9-633e53238adf.png)

**Comment by alexeyzimarev** [comment]
I keep asking you about the response content when you get an error, could you please check what the server returns to you?

**Comment by alexeyzimarev** [comment]
What does this code mean, do you know?
![image](https://user-images.githubusercontent.com/2821205/150776122-49e58697-1df0-45b9-8f64-49298cd903e0.png)

**Comment by alexeyzimarev** [comment]
Your code with RS 106 is making this request:
![image](https://user-images.githubusercontent.com/2821205/150777539-db8713aa-f966-4fde-84cb-e1e7f018bc52.png)

Same, with RS 107 latest alpha:
![image](https://user-images.githubusercontent.com/2821205/150777609-487ec9af-974c-45a1-b58f-50b4a9187b72.png)

**Comment by alexeyzimarev** [comment]
The only difference I have seen before is `filename*=utf-8....` and it is gone now. The only difference right now is that the parameter name and file name are not quoted. I can make this as a final change, further on I have no idea what could be wrong. If the next alpha won't work again, I'd say you need to ask the server owner/vendor.

**Comment by alexeyzimarev** [comment]
Here's the request made with 107.1.2-alpha.0.18

![image](https://user-images.githubusercontent.com/2821205/150779402-f734b588-951e-49fb-9ecb-e029a2d5a30e.png)

You can see those requests for yourself here https://requestbin.com/r/enp1nn2lipju/248wgSbG7XvRjoAPT7teiswbRUn

**Comment by bfcavaco** [comment]
I'm gonna check with the server maintainer what that StatusCode mean.
I seams that the problem is on the server side, some parameter that I must specify.
I'll give feedback as soon they answer me.

**Comment by bfcavaco** [comment]
Good news,
It's working on version this last version 107.1.2-alpha.0.18
Possibly was that quoted filename you referred.
The same code is working now.

**Comment by alexeyzimarev** [comment]
Nice. I'm glad that we found the root cause.

**Comment by bfcavaco** [comment]
> Nice. I'm glad that we found the root cause.

Thanks a lot :)
