### ISSUE TITLE
AddCookie extension method throws ArgumentException

### ISSUE THREAD

**Issue by fabianschurz** [restsharp/RestSharp#1733]
**Describe the bug**
Calling the extension AddCookie on RestClient throws an exception that says cookie.Domian is not allowed to be null.

**To Reproduce**
Call AddCookie on client

**Expected behavior**
No exception is thrown in general. Overload where you can also set path and domain or a complete replacement.

**Stack trace**
System.ArgumentException: The parameter 'cookie.Domain' cannot be an empty string. (Parameter 'cookie')
   at System.Net.CookieContainer.Add(Cookie cookie)
   at RestSharp.RestClientExtensions.AddCookie(RestClient client, String name, String value)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - .NET version: .NET 5
 - Version: 102.2.1

**Additional context**
Workaround for me is to add the cookie myself to the CookieContainer as you are able to set a domain there.

**Comment by alexeyzimarev** [comment]
Hey @fabianschurz I already fixed it :)
https://github.com/restsharp/RestSharp/releases/tag/107.2.1

**Comment by namilkimfree** [comment]
It also happens in 107.2.1, 108.0.1

**Comment by alexeyzimarev** [comment]
It will happen if you ignore the null reference warning and pass the null value. The issue was that these parameters were impossible to pass. You have to specify a not-null domain. It's not RestSharp that throws, you can see that the extension is one line of code:
https://github.com/restsharp/RestSharp/blob/ebb1df1cb919466e6490175afb028a16e262ac40/src/RestSharp/RestClientExtensions.Config.cs#L55-L61
