### ISSUE TITLE
RestClient constructor: baseUrl property

### ISSUE THREAD

**Issue by cosmoscowboy** [restsharp/RestSharp#1765]
In the previous version 106.11.7, the RestClient had a property BaseUrl, but this has been removed since version 107.3.0. Is it possible to add this back to RestClient as a '**_get_**' property?

 I use exports from Postman to send a HttpRequest via RestSharp. The request from Postman contains an absolute Uri. Before sending a RestRequest, I check if the RestClient defines a BaseUrl, and if so, I remove it from the postman request, so that the relative URL is sent in the constructor of the RestRequest. This is no longer possible. I am now forced to use the constructor containing RestClientOptions, as this contains the BaseUrl. 

It seems that all of your documentation creates a RestClient with a base URL, so that the relative URL is sent in the RestRequest. This is logical, as it matches the idea of creating the HttpClient as a singleton, and just sending RestRequest's each time.

**Comment by cosmoscowboy** [comment]
In my previous post I wrote:

`This is no longer possible. I am now forced to use the constructor containing RestClientOptions, as this contains the BaseUrl.`

However, the RestClient doesn't contain a property to the RestClientOptions either, so I am still unable to check what the 'BaseUrl' of the RestClient is!

**Comment by alexeyzimarev** [comment]
I am unsure why do you need to check if the base URL is set or not. It's your client instance, don't you know how it is instantiated?

**Comment by cosmoscowboy** [comment]
The startup file of the .NET core application is creating an instance of the RestClient, so yes, technically another library that uses that client to send a request (that is imported from Postman), doesn't know if the RestClient has a base URL or not. When I read in the URL of the Postman request, it will always contain a host.

Question: assuming the RestClient is instantiated with a BaseUrl, and I create a RestRequest with a resource that is an absolute URL (UriKind.Absolute), is the client smart enough to remove the host, and send on a relative URL? If that is the case, then I would need to do that checking myself.

**Comment by alexeyzimarev** [comment]
The issue you might face is each `RestClient` instance may be configured differently. By reusing an instance you would encounter unexpected behaviour. Say, you have an instance with an authenticator for Twitter, but you call Instagram, what then? Each particular use case needs an instance of `RestClient` that is controlled by that use case. That's why I keep advocating to use specific client API classes, wrapping their own `RestClient` instances, and not exposing `RestClient` out. https://restsharp.dev/usage.html#recommended-usage

**Comment by cosmoscowboy** [comment]
Hi @alexeyzimarev , there are different parts of the application that use their own RestClient, each using a different BaseURL, so that is really not the problem. I see this issue simply being:

1. When you supply a value to a constructor, you generally provide a getter for that value.

If not, then I would expect that the library is smart enough to resolve this issue:

_var restClient = new RestClient("http://baseurl.com");
var restRequest = new RestRequest("http://baseurl.com/my-relative-url");_

The rest request should still be sent, because the client knows whether it was created with a base URL or not.

If your examples recommend creating a RestClient with a base URL, why is there a constructor not accepting any parameters?

**Comment by IanElsinga** [comment]
I also would like access to the client's options if possible.

My situation is that I have a collection of clients for different purposes, as suggested above, and I need to know what the base url is for those for logging purposes, to verify what the BaseUrl actually is for the client currently being used for troubleshooting etc.  Could there not be a way to access the client's options for that purpose?  It could certainly be read-only.  Otherwise, I have to change my collection to a class containing the client and the client options - I have to drag those options objects around with the client objects. 

Thanks for considering!

**Comment by christofcolle** [comment]
I agree with Ian's proposal here above.
I also would need to be able to access the "BaseUrl" property for logging purposes. Be it through a direct `RestClient` (read-only?) property, or through the `RestClientOptions` object, I don't really care... As long as I'll be able to access it again _somehow_.

**Comment by kendallb** [comment]
I am looking at trying to move out code over from 106.x to 107 and due to the changes to start using HttpClient internally and the desire to NOT instantiate lots of HttpClient instances, the goal is to re-use RestClient over and over. Now HttpClient on the one hand is designed to be used over and over (and honestly it's a freaking pain to get it right!) and it's thread safe. You can make calls from multiple threads concurrently to the same instance. 

https://docs.microsoft.com/en-us/archive/blogs/henrikn/httpclient-httpclienthandler-and-webrequesthandler-explained

However HttpClient for that reason has the option to create it without a base URL at all because you can call SendAsync() to send requests to it and pass everything you need in the request itself. But RestSharp does not. You are expected to pass a base address to the HttpClient, which then effectively means you CANNOT re-use a single instance of HttpClient throughout your code? The goal is to not have lots of instances of HttpClient, but it seems the approach taken with RestSharp v107 is to force you to pass in a base address for the client instance, which now means you either need to create a new instance for every service you want to connect to, or worse, folks porting blindly from v106 and earlier will simply create a new instance for every request and end up with huge problems. 

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

In reality I think this is a bad design. I think the correct solution to enforce a single instance is to allow to be a REAL single instance in your app, where there is just one instance of HttpClient used over and over for all requests, and everything needed to make a request is defined in RestRequest(), including the base URL. 

At this point I might just give up on this porting process and come back to it another day. I already wrestled with HttpClient once already for the ShipEngine client we built and it was not fun. It's going to be quite a lot of work to change our code to force every client we use to be single instance, one for every service we connect to. At least I can pass in my existing single instance of HttpClient as there is an overload for that, but there there is this:

```
    void ConfigureHttpClient(HttpClient httpClient) {
        if (Options.Timeout > 0) httpClient.Timeout = TimeSpan.FromMilliseconds(Options.Timeout);
        httpClient.DefaultRequestHeaders.UserAgent.ParseAdd(Options.UserAgent);
    }
```

The last thing we want to be doing is setting any default request headers on a SHARED HttpClient instance? Any request headers should be set as part of the request processing, not as part of the base HttpClient instance that is used to send the requests. That only works if you are not expecting it to be shared, yet there is an overload to pass in a shared HttpClient instance.

**Comment by kendallb** [comment]
Following up on this, the only way to set the BaseUrl (and BaseHost) for request with v107 is via the RestClientOptions class, which you pass to the constructor of RestClient. It would be tempting to simply stash a copy of that somewhere so you can adjust the options for each request, but that would NOT be be thread safe and clearly not expect as the options are not exposed via the RestClient class itself.

**Comment by IanElsinga** [comment]
Could the BaseUrl be made available read-only (for logging purposes for example) by adding the following line to the `RestClient` class?  I did try this and it seemed to work although I did not run all tests.

`public Uri? BaseUrl => Options.BaseUrl;`

**Comment by kendallb** [comment]
It could, but honesty I think this design is broken unfortunately. The more I think about it the more I think the decision to go from a lightweight client per request model in v106 and earlier to a single instance, non-shareable RestClient is bad design. The RestClient should have remained as an instance per request like before, but internally allow for sharing a single instance HttpClient (optionally passed in) and then configure everything needed for each request when the requests are made.

And don't get me started on the removal of all the interfaces (IRestResponse etc). Sure, someone does not like the idea of people mocking Rest client library code, but the old code was written that way so that is a HUGE breaking change that makes it virtually impossible to refactor around easily.

**Comment by alexeyzimarev** [comment]
@kendallb the article you've read is correct, but your conclusion is not exactly so.

It's perfectly fine to use a `RestClient` instance as a singleton. But it's not `HttpClient` that is a problem with instance per request, it's `HttpMessageHandler`. RestSharp has an instance of `HttpMessageHandler` created based on `RestClientOptions`. `RestClient` will _not_ use the updated version of the options even if you manage to do it via reflections. It will, however, use some of the options per request, which are mostly around error handling.

What the article doesn't explain well, is the fact that you _can_ have multiple instances of `HttpClient` (and `HttpMessageHandler`), but not per request. Say your application uses three APIs. It is perfectly fine to create three instances of `RestClient` and use them. As soon as it's not _per request_ - you are good.

That's the exact reason why I promote using typed clients (with interfaces, if necessary), as described in the docs. Each API might require different settings, so you get different instances with different configuration.

**Comment by alexeyzimarev** [comment]
> The RestClient should have remained as an instance per request like before

Your assumption is incorrect. It was never working like that, it was fundamentally broken, and lots of issues of hanging connections were reported, caused exactly by that. RestSharp was using `HttpWebRequest` that is wrapping `HttpClient` with a number of message handlers cached internally based on settings, which never worked properly. Microsoft people admitted that it's a hack just to keep legacy code working somehow, it was a poor-man cache.

When it goes to the interfaces rant, please keep it out of this issue.

**Comment by alexeyzimarev** [comment]
> It would be tempting to simply stash a copy of that somewhere so you can adjust the options for each request

But why? You can set an empty base URL and then use the absolute URI for the request, no?

**Comment by alexeyzimarev** [comment]
> internally allow for sharing a single instance HttpClient (optionally passed in) and then configure everything needed for each request when the requests are made.

I think I can make the constructor that accepts the `HttpClient` instance not to change anything in the passed client.

**Comment by alexeyzimarev** [comment]
For those interested, check this one. https://github.com/restsharp/RestSharp/pull/1782

**Comment by MikePrime21** [comment]
I've run into an issue where I'm writing a desktop client.  We allow the user to change the server url on the client.  Right now the problem is that once we load the wrapped up RestClient through DI as a singleton on startup, we can no longer change the base url for that instance.  Right now, after the server url is changed I save to to the config file then force a restart of the application.  Is there any other way for me to work around this, or would this change be what I need?

**Comment by kendallb** [comment]
> > The RestClient should have remained as an instance per request like before
> 
> Your assumption is incorrect. It was never working like that. It was fundamentally broken, and lots of issues of hanging connections were reported, caused exactly by that. RestSharp was using `HttpWebRequest` that is wrapping `HttpClient` with a number of message handlers cached internally based on settings, which never worked properly. Microsoft people admitted that it's a hack just to keep legacy code working somehow, it was a poor-man cache.

You are completely missing the point of what I was saying. RestClient SHOULD NOT have been changed from instance per request to a single instance per API entry point. I am NOT saying that we should not be changing to using a single instance of HttpClient internally to solve the problems that plague HttpWebRequest. What I am saying is that by changing the way someone actually USES the library, it is now effectively broken for the millions of users who have been using it as an instance per request since day one, as that really the only way to effectively use it.

By changing this to a single instance per API entry point, someone has made the decision to enforce THEIR design pattern on the rest of us, and IMHO that is no acceptable. That design pattern would not have been possible with the old instance as it was not thread safe, so the only safe option was to use an instance per request. And changing RestClient so it CAN be used a a single instance per API entry point itself is not a bad goal, but completely forcing everyone who uses the library to REWRITE THEIR CODE is wrong. Just plain wrong.

What I was (clearly unsuccessfully) trying to point out is that RestClient should remain usable as a single instance per request, but internally it should be changed to use a single instance of HttpClient. This could be done without any of the baggage of requiring RestOptions (another code re-write for us), and there could be a new overload to create an HttpClient to pass in your own single instance of HttpClient if you want. If you don't, it will use the internal single instance.

The way it is now, ANYONE trying to migrate from RestSharp v106 and lower (millions of developers), is forced to implement quite a drastic code re-write to be able to use it. It is ENTIRELY NOT TRIVIAL. I know, as I have already tried. It's going to be significant amount of work for us to refactor our code as we have to completely re-think and re-write our entire REST pipeline for all the API's we communicate with. We have to work out a new way of instantiating a single instance per API request, or find ways to refactor our code to set the resource for requests to the FULL URL now, not just the relative URL from the base we set up in the client. It's a lot of work. And IMHO completely unnecessary as the goal of changing to use a single instance of HttpClient internally is totally achievable without forcing everyone to re-write their code.

Since v107 is now the active version of RestSharp, not only do I have the problem of trying to port my own code, but what happens when I now import a third party library that also relies on the RestSharp library? I can no longer use a binding redirect to force that library to use v107+, because if that library is using v106 or earlier, IT WILL BREAK!

Since v107 is now the active version, is anyone maintaining and doing bug fixes for v106? I doubt it. So what happens if we find a critical vulnerability in RestSharp that exists in v106 and earlier. Nobody can produce a patch for it, so the only option is to patch v107, but then all the millions of developers now exposed to this flaw CANNOT upgrade to v107 without a significant code rewrite. We cannot simply load up Nuget and update to the latest library, recompile and deploy with the fixes.

> When it goes to the interfaces rant, please keep it out of this issue.

Its related because it covers the same issue. Someone deciding to changing something to fit THEIR preferred design pattern, which breaks the code for everyone else. But I will open a new issue for that.

**Comment by MikePrime21** [comment]
> You are completely missing the point of what I was saying. RestClient SHOULD NOT have been changed from instance per request to a single instance per API entry point.

Perhaps I'm missing something, but you can still use it in an instance based manner.  You can load HttpClient as a singleton but create new instances of the RestClient using the constructor below.  That would allow you to put RestClient into a using statement, but still not dispose of the underlying HttpClient.   Don't get me wrong, it still breaks existing code basses and requires rework, but it doesn't for a change in the design pattern.

`public RestClient(HttpClient httpClient, RestClientOptions? options = null, bool disposeHttpClient = false)`

**Comment by kendallb** [comment]
> Perhaps I'm missing something, but you can still use it in an instance based manner. You can load HttpClient as a singleton but create new instances of the RestClient using the constructor below. That would allow you to put RestClient into a using statement, but still not dispose of the underlying HttpClient. Don't get me wrong, it still breaks existing code basses and requires rework, but it doesn't for a change in the design pattern.
> 
> `public RestClient(HttpClient httpClient, RestClientOptions? options = null, bool disposeHttpClient = false)`

Sure, but a) it was not designed to work that way and b) it still breaks all existing code you might have that relies on RestSharp v106 and earlier.

**Comment by cloudhunter89** [comment]
This is the nature of any library.  To varying degrees the owners of the
libraries enforce their design decisions on any client code.  The client
often has little or no say in these decisions.

I find irony in the argument about forcing design decisions, coming from a
user of the library.

**Comment by kendallb** [comment]
> This is the nature of any library. To varying degrees the owners of the libraries enforce their design decisions on any client code. The client often has little or no say in these decisions. I find irony in the argument about forcing design decisions, coming from a user of the library.

Why is that ironic exactly? The users of the library are in fact the target market for the library. Design decisions that make it difficult for the users of the library to successfully upgrade to a later release need a major rethink. 

At this point it might be more fruitful for me to simply fork it and use my own version in my own code, and let all the other library developers who use RestSharp come to their own conclusions about whether it is still worth relying on this library.

**Comment by MikePrime21** [comment]
You can try to write an adapter around the existing RestClient rather than maintain a fork.  It sounded like the previous version had serious hanging connection issues.  Unfortunately since the new version no longer uses interfaces, it may be difficult to get all the extension methods to work unless you inherit from the RestClient.  Even if you do inherit from RestClient, none of members are virtual so you can't override them.

**Comment by kendallb** [comment]
I am not sure building an adapter is really feasible to be honest. I am going to try reverting all the unnecessary changes and converting the guts to use HttpClient and see how far I get. Basically I will try to implement what I believe is the approach that should have been taken so that existing code will continue to function AND be able to resolve the hung connection issues without requiring a complete re-write.

**Comment by alexeyzimarev** [comment]
I will pretend I have not seen and not laughed about the "target market" sentence. I must be completely off this world now as I thought "market" is something where one pays and the other gets paid.

Nevertheless, I find it frustrating that I made a PR and asked people who participate in this issue to see if it is solving any of their issues. There's no feedback.

**Comment by IanElsinga** [comment]
The original issue here is regarding the accessibility of the `BaseUrl` property, which you have addressed perfectly, Alexey.  Thank-you.

**Comment by kendallb** [comment]
> I will pretend I have not seen and not laughed about the "target market" sentence. I must be completely off this world now as I thought "market" is something where one pays and the other gets paid.

Since I hijacked this feature request away from it's original goal, I will simply leave it alone and continue the discussion in my other feature request.

> Nevertheless, I find it frustrating that I made a PR and asked people who participate in this issue to see if it is solving any of their issues. There's no feedback.

I certainly looked it over, but it was not something I needed. For those that want read only access to the BaseUrl, I believe it will suit their purposes just fine.

**Comment by alexeyzimarev** [comment]
Made a change, it's available in the latest preview packages. Wil release at some point next week.

**Comment by kendallb** [comment]
@alexeyzimarev a couple of issues with the current implementation. RestClientOptions is now fully public and the BaseUrl value has a public setter. Since you cannot actually change this value after your client is constructed, I recommend it be changed to an internal setter. 

The BaseHost value is public and can be changed, and it is used when the message is sent. So theoretically while a user like myself can change client.Options.BaseHost for every request it does seem like a bit of a Kludge to do so. Not sure of a cleaner option. PR is here:

https://github.com/restsharp/RestSharp/pull/1785

**Comment by alexeyzimarev** [comment]
You're right, those properties should be init-only.

**Comment by kendallb** [comment]
Init only should work, but it does have issues of not working with earlier C# compilers if the client code needs to set it:

https://github.com/restsharp/RestSharp/pull/1788

**Comment by alexeyzimarev** [comment]
Yeah, I remember that one. But it seems like people get it fixed. The `RestResult` is a record with `init` instead of `set`, which caused some issues that are reportedly resolved (the issue you mentioned, and one SO question).

There's one impediment for both `init` and `internal set`. I thought of making a factory with a configuration delegate, similar to what Microsoft is doing in many cases (`cfg => cfg.ThrowOnAnyError = true`). It would only work with public setters. In that case, those properties need to get converted to read-only properties of the client itself, instead of exposing `Options` as a public property.
