### ISSUE TITLE
Restsharp not decompressing gzip response

### ISSUE THREAD

**Issue by anibal-acosta** [restsharp/RestSharp#1845]
I am using restsharp v107.3.0 
When response is in gzip encoding, restsharp give me the content without decompress.
I tried setting the option **AutomaticDecompression** to **All** with the same result.
In postman app the response is presented decompressed.

Response Headers are:
![image](https://user-images.githubusercontent.com/29735109/166591342-5cba2fab-3234-4e87-9490-2ff31a21f64f.png)

And the decompressed body is a json string

Same response is decomressed and works fine with RestSharp v106.12.0

**Comment by omikhailov** [comment]
WTH the issue is closed? RestSharp 110.2 still fails to decompress gzip responses!

**Comment by alexeyzimarev** [comment]
@omikhailov

1. The issue was closed due to inactivity. It is a community project, and in a lack of contributions, particular issues get closed.
2. There are tests for deflate and gzip encoding, which pass on all supported targets, both for Windows and Linux. The issue didn't provide any information about the payload, which makes it impossible to diagnose.
3. You got very close to violate the [code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct). Please watch your tone.
