### ISSUE TITLE
Memory leak ExecuteAsync when using AddXmlBody

### ISSUE THREAD

**Issue by slagtejn** [restsharp/RestSharp#1914]
Memory is never released when using ExecuteAsync.  Run in a loop and you will see memory increases, but never releases after GC.  

data in the below example is an XElement.

```csharp
RestRequest request = new RestRequest("***", Method.Post);
request.RequestFormat = DataFormat.Xml;
request.AddXmlBody(data);
```

```csharp
for (int i = 0; i < 10000; i++)
{
      await client.ExecuteAsync(request);
}
```

Workaround is to pass in a string representation of the XElement to AddXmlBody.

- OS: Windows
- .NET version: .NET 6
- Version: 108.0.1

**Comment by ericnewton76** [comment]
I've identified the problem more with using XmlSerializer and not ExecuteAsync.

The problem is `new XmlSerializer(typeof(T)` keeps creating new assemblies to handle serialization instead of being smart and attempting to reuse a generated assembly that works for that type.  This is partially due to dynamic-ness of xml.  Another example of this here, specifically more in the last half of the article, starting with **Unmanaged memory leaks made by the .NET runtime itself**
https://www.deleaker.com/blog/2021/03/19/unmanaged-memory-leaks-in-dotnet/
