### ISSUE TITLE
.NET MAUI iOS "Operation not supported on this platform"

### ISSUE THREAD

**Issue by vladsava87** [restsharp/RestSharp#1918]
**Describe the bug**
In a .NET MAUI project running on iOS, creating an new instance of RestClient, throws an "Operation not supported on this platform" exception.
Android works as expected.

**To Reproduce**
Create new .NET MAUI project, add RestSharp nuget and create new RestClient object.
Run project on iOS configuration.

**Expected behavior**
Create a new instance of RestClient

**Stack trace**
   at System.Net.Http.NSUrlSessionHandler.set_Proxy(IWebProxy value)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClientHandler.InvokeNativeHandlerMethod(String name, Object[] parameters)
   at System.Net.Http.HttpClientHandler.SetProxy(IWebProxy value)
   at System.Net.Http.HttpClientHandler.set_Proxy(IWebProxy value)
   at RestSharp.RestClient.ConfigureHttpMessageHandler(HttpClientHandler handler)
   at RestSharp.RestClient..ctor(RestClientOptions options, Action`1 configureDefaultHeaders)
   at RestSharp.RestClient..ctor()
   at MauiAuth0App.MauiProgram.CreateMauiApp() in /Users/vladsteer73/Work/R&D/dotnet-maui-auth0-app-main/MauiProgram.cs:line 32

**Desktop (please complete the following information):**
 - OS: macOS
 - .NET 6
 - Version 6.0.400

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/13381967/188165879-6ec9e9c1-90fb-4947-88b5-b8eb9b9a0800.png">

**Comment by FirewizzNL** [comment]
Got the same issue

**Comment by vadd98** [comment]
I have the same issue and I had to move to use the HttpClient in System.Net.Http

**Comment by FirewizzNL** [comment]
Thanks, I will move to too. After a bit of searching it looks like this has been like this for ages

**Comment by SebastianGrief** [comment]
Setting the `handler.Proxy` in [RestClient.cs:142](https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/RestClient.cs) is causing that because custom proxies are not allowed in [NSUrlSessionHandler:625-628](https://github.com/xamarin/xamarin-macios/blob/main/src/Foundation/NSUrlSessionHandler.cs)

So adding `if(handler.SupportsProxy) handler.Proxy = Options.Proxy;` in RestClient fixes the instance creation.
I've not yet tested that any further tho.

**Comment by dennisarriola** [comment]
Hello, I am experiencing this too. Hope this will be supported by RestSharp in their next release.
I'm using 108.0.1 by the way.

I tried SebastianGrief possible fix, it did not fix the issue.

**Comment by alexeyzimarev** [comment]
> Thanks, I will move to too. After a bit of searching it looks like this has been like this for ages

For's been there for ages is irrelevant as RestSharp doesn't work as it used to.

Thanks @SebastianGrief for the tip, mind opening a PR?

**Comment by dennisarriola** [comment]
Hello,

Is the fix included in v108.0.2 release?
I am using the library from nuget.

**Comment by alexeyzimarev** [comment]
https://github.com/restsharp/RestSharp/releases/tag/108.0.2

**Comment by dennisarriola** [comment]
Hello @alexeyzimarev 

I tried v108.0.2 and it throws Timeout error.
Here's the exact error message, "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."
I'm not sure if I missed something, but it works perfectly fine in Android and in Windows platforms. This only happens in iOs platform.

Do you have any idea on how to resolve this? 

Thank you very much.

**Comment by dennisarriola** [comment]
Hello, 

We would like to follow-up, if .NET Maui iOS platform is already supported by this fix?
Thank you.

**Comment by alexeyzimarev** [comment]
<img width="913" alt="Screenshot 2022-09-29 at 13 19 44" src="https://user-images.githubusercontent.com/2821205/193018354-635b8d40-5a95-450e-9906-9527e38c9a25.png">

**Comment by alexeyzimarev** [comment]
The fix resolved the "Operation not supported on this platform" issue with the proxy. That's what issue was about, and that's why it's closed.

**Comment by dennisarriola** [comment]
I see. Thank you for reply @alexeyzimarev.
Guess .NET Maui iOs platform is still not supported.
