### ISSUE TITLE
RestClient is not configured correctly

### ISSUE THREAD

**Issue by orbis-pbowman** [restsharp/RestSharp#2161]
**Describe the bug**
The options set on the RestClient are ignored as they should be set on the RestClientOptions passed to the RestClient constructor. In previous versions of RestClient, it was possible to set options on the RestClient instance directly and even after construction these would be used. In newer versions of RestClient, including that used in 0.0.1.28 of this package, only the options passed into the constructor are used to configure the HttpClient - any set later are ignored. This library does that - it builds but it doesn't work. The newest version of RestClient makes it a compile time issue by copying the options to a read only version of the options.

In our case, we use a proxy, and it would be nice to set other options on the RestClient too.

**To Reproduce**
Use the library and see the proxy and other others not being set correctly.

**Expected behavior**
The options should be set when RestClient is constructed.

**Comment by orbis-pbowman** [comment]
I should add that we're upgrading from 0.0.1.5 to 0.0.1.28 due to the (request-target) issue that must be resolved by 22 Jan, so time is of the essence for this fix.

**Comment by alexeyzimarev** [comment]
Sorry I am not aware of versions 0.0.1.5 to 0.0.1.28 of RestSharp. I believe `RestClientOptions` were introduced somewhere at v107 and the latest is v110.

Using `RestClientOptions` must follow the Options pattern, which is widely adopted in ASP.NET Core. Options _cannot_ be changed after the client is instantiated, because changing the options essentially requires creating a new client instance. As you rightfully mentioned, properties of `RestClientOptions` have setters, and previously `IRestClient.Options` used the same type, but it was changed for the reason you describe, so all the properties in the `IRestClient.Options` are read-only.

Indeed, you can pass an instance of the options class to the constructor and try changing it later, and it will not work. And I do not consider it as a bug because if you pass something to a constructor, you expect the instance to be _constructed_ using the values you passed. The options class is just a way to avoid having 30 constructor arguments, and it should not be used to change something inside the options object after the client instance is constructed, because it would be similar to expecting the constructor to be recalled after the object has already been constructed.

I am also not sure what dates and releases you are referring to. I think you probably confused an open-source community project repository with something that belongs to your organisation.

**Comment by orbis-pbowman** [comment]
Oh, I do apologise. You're correct - this was intended for another project (a large payment provider's SDK) not internal to my company, but I had both GitHub repos open and raised the issue in the wrong one. Sorry for taking your take.

**Comment by alexeyzimarev** [comment]
No worries, I figured that out :)
