### ISSUE TITLE
async/await support for ExecuteAsync 

### ISSUE THREAD

**Issue by jacdevos** [restsharp/RestSharp#626]
One of my clients really likes using the async/await feature added to C# 4.5 onwards. It sometimes simplifies async code and testing a bit. 

Do you think support for it will be a useful addition to RestSharp?

The way I see it, all we need is 2 new methods in IRestClient that mirror the existing ExecuteAsync methods, but returns a Task instead of having a callback in parameter.

We already have a simple working version of that we can contribute if there is interest.

**Comment by hallem** [comment]
There is already support for this.  There are several execute methods on the RestClient that return tasks.  I apologize the documentation is a little lacking, I'm still working on it.  Take a peek at the code or though the object browser or intellisense and pick the one you need.

**Comment by jacdevos** [comment]
Thanks - I see it's nicely supported.

Let me know if you need help with any of the open features/bugs.

On 8 January 2015 at 00:15, Michael Hallett <notifications@github.com>
wrote:

> There is already support for this. There are several execute methods on
> the RestClient that return tasks. I apologize the documentation is a little
> lacking, I'm still working on it. Take a peek at the code or though the
> object browser or intellisense and pick the one you need.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restsharp/RestSharp/issues/626#issuecomment-69102363>.
>



-- 
Jacques de Vos
+27 72 587 6401  Mobile
+27 86 669 2757  Fax

**Comment by hallem** [comment]
Hey I always need help so if you see something that you're up for doing a PR on, go for it!

**Comment by dgreene1** [comment]
In case anyone is arriving here as well, I believe this is the code that makes async await possible:
https://github.com/restsharp/RestSharp/blob/e7c65df751427298cb59f5456bbf1f59967996be/RestSharp/RestClient.Async.cs#L202

The tests that show how it's used:
https://github.com/restsharp/RestSharp/blob/e7c65df751427298cb59f5456bbf1f59967996be/RestSharp.IntegrationTests/AsyncTests.cs#L63

**Comment by Neutrino-Sunset** [comment]
Still no demonstration of this in the documentation.

**Comment by SamerAlRawi** [comment]
not sure if documentation was updated or not, but that's the [stackoverflow answer](https://stackoverflow.com/questions/21779206/how-to-use-restsharp-with-async-await) - how to use the async overload!

**Comment by Alexabix** [comment]
> not sure if documentation was updated or not, but that's the [stackoverflow answer](https://stackoverflow.com/questions/21779206/how-to-use-restsharp-with-async-await) - how to use the async overload!

There's still no documentation on `ExecuteAsync` and the `ExecuteTaskAsync` example from this SO answer is currently marked as obsolete

**Comment by alexeyzimarev** [comment]
Not really sure what you mean. All methods are properly documented with XML comments and everything that the client does can be easily found at the interface.

Here is the `ExecuteAsync` method:
https://github.com/restsharp/RestSharp/blob/master/src/RestSharp/IRestClient.cs#L169

**Comment by 18549** [comment]
This is the documentation
https://restsharp.dev/getting-started/#basic-usage

All examples appear to be synchronous, which is not how modern webservices are commonly implemented.

The unit tests are a terrible example of how to use this in production code since the tests themselves are also synchronous and resort to a Task.Wait() followed by Task.Result hence blocking to get the result.

**Comment by alexeyzimarev** [comment]
I haven't mentioned unit tests by the way. I was referring to the XML comments on methods for `IRestSharp`. Essentially, `Execute` and `ExecuteAsync` are identical. `ExecuteAsync` returns the `Task<IRestResponse<T>>` instead of `IRestResponse<T>`, which is kind of obvious, and also accepts the cancellation token.

To be honest, I was working hard during the last couple of weeks, alone, to align APIs, fix issues, publish new serializers and move the docs to a better place. I'd love to get contributions now. The docs are in the repo, so feel free to add what's missing.
