### ISSUE TITLE
Deserialize a DateTime not using DateTimeStyles

### ISSUE THREAD

**Issue by viruscamp** [restsharp/RestSharp#691]
There are 3 ways to deserialize a DateTime
1. RestSharp/SimpleJson.cs
   RestSharp.PocoJsonSerializerStrategy.DeserializeObject(object value, Type type)
   dateTimeStyle = DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal
   Will get a DateTime.Kind = UTC
2. RestSharp/Deserializers/JsonDeserializer.cs
   RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, object value)
   dt = DateTime.ParseExact(stringValue, DateFormat, Culture);
   dateTimeStyle is not used.
   Will get a DateTime.Kind = Unspecified
3. .RestSharp/Extensions/StringExtensions.cs
   RestSharp.Extensions.StringExtensions.ParseFormattedDate(string input, CultureInfo culture)
   dateTimeStyle = DateTimeStyles.None
   Will get a DateTime.Kind = Unspecified

It should use dateTimeStyle = DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal all the 3 ways.

BTW, it's hard to customize my own DateTime Deserializer .

**Comment by AgentMC** [comment]
@viruscamp : great finding! I also have problems with this issue. :+1: 
Do you guys have any time estimations on making the behavior consistent?

I'm interested since my tests depend on Rest# and now I from time to time get assertion errors since DateTime is usually returned as Unspecified/Local, but when datetime is specified without fractional part it's UTC. To solve this I have to use .ToUniversalTime() everywhere, but it'd be nice to have this consistent.

**Comment by hallem** [comment]
Nice catch.  I'll add this to the list of things to fix.

**Comment by AgentMC** [comment]
Guys, in 105.2.3 UTC datetime is still not deserialized consistently.
"2015-11-27T13:45:51.577Z" -> DateTimeKind.Local on both 105.1.0 & 105.2.3
"2015-11-27T13:44:57Z" -> DateTimeKind.Unspecified on 105.1.0 & DateTimeKind.UTC on 105.2.3
:(

**Comment by alexeyzimarev** [comment]
Fixed by #708
