### ISSUE TITLE
MonoTouch in the NuGet

### ISSUE THREAD

**Issue by mattleibow** [restsharp/RestSharp#740]
Love the new update with the Xamarin platforms, but why is the monotouch directory empty? Is this intentional? The csproj is there.

**Comment by hallem** [comment]
matt the directories are empty because we use file links to in the projects to keep all the source files in one spot.  all the source files are in the main restsharp directory.  the csproj files link to them and are needed only for build to define compile time constants and the different framework editions.

**Comment by mattleibow** [comment]
@hallem I was talking about the NuGet. It has no assembles in the lib\monotouch10 directory.

**Comment by hallem** [comment]
hmm... so when you installed the latest version the monotouch10 directory is empty (i.e. packages/RestSharp/monotouch10)?

**Comment by mattleibow** [comment]
@hallem Yes.

**Comment by mattleibow** [comment]
I found the issue: https://github.com/restsharp/RestSharp/blob/master/build.bat#L75

**Comment by hallem** [comment]
silly copy paste error
