### ISSUE TITLE
PostTaskAsync<T> ignores server errors

### ISSUE THREAD

**Issue by CoolDadTx** [restsharp/RestSharp#967]
When using PostTaskAsync<T> to make a request, if the server fails the call then the method still returns back an instance of T set to default values. The server error doesn't trigger exceptions or otherwise indicate in any way that the returned object is simply a new instance created by the client.

ExecuteTaskAsync<T> does have the correct status code and the content is the error body, if any. But Data contains a new'ed instance of T which is what the extension seems to be returning instead of reporting the error.

**Comment by alexeyzimarev** [comment]
Would be great if you can write a test that demonstrates the issue.

**Comment by alexeyzimarev** [comment]
I don't think the issue is valid. If you need to get a hold of the response, you can just use `ExecuteGetTaskAsync`, which has the same signature but returns the full response. I see the point that we probably should have raised an exception but it is hard to do now since I would expect quite a lot of code running in production that doesn't expect any exception from this call.

If you have a suggestion on how to fix this, I'll happily consider.

**Comment by CoolDadTx** [comment]
Sounds reasonable and consistent with how other clients work. Thanks.

**Comment by alexeyzimarev** [comment]
New methods are available in 106.4 on NuGet.
