### ISSUE TITLE
Timeout/ReadWriteTimeout ignored

### ISSUE THREAD

**Issue by darxis** [restsharp/RestSharp#974]
Environment: RestSharp v105.2.3 with .NET Framework 4.5.2

I am consuming an HTTP API action and sometimes it blocks forever (Fiddler shows it never completes). So, to handle this I have set the `RestClient` `Timeout` and `ReadWriteTimeout` to 10000 ms, but it seems that these timeout values aren't taken into consideration, because the request timeouts after 100 seconds, that is by default.

The requests and responses send are very small, no more than several KB.

Same problem described here: https://stackoverflow.com/questions/44109895/restsharp-restclient-ignores-timeout

**Comment by darxis** [comment]
![restsharp_bug](https://user-images.githubusercontent.com/10614436/28691479-66809a6e-731d-11e7-8058-81c679c3ad90.png)

Screenshot of request statistics in Fiddler. It shows that the server has not started to send the response.

**Comment by Timyrlan** [comment]
Same here

**Comment by SkabbMask** [comment]
I have the same problem, anyone know why this is happening, and if there's a wayto fix it?

**Comment by alexeyzimarev** [comment]
Can you try the async calls, timeouts should definitely work there.

**Comment by alexeyzimarev** [comment]
This test passes https://github.com/restsharp/RestSharp/blob/develop/RestSharp.IntegrationTests/AsyncTests.cs#L200

Is there anything in your code that is different from the test code?

**Comment by maplemale** [comment]
Same issue. This issue seems to come up a lot and I seem to be able to work around it by validating the Request and Client timeouts are both set. Setting just the Client Timeout for instance does not seem to do much.

Without really digging too far into the RestClient class, what is the difference between the Client level timeout and the Request level timeout?

**Comment by boylec** [comment]
Same issue. I set the timeout on the client as well as the request I am executing to Timeout.Infinite (-1), but the response I get in the ErrorException property of the response is a WebException with the message: "The operation has timed out".

**Comment by boylec** [comment]
Yes, no problem I understand your frustration.

I did review the code in the test you mentioned and my own code is following the same exact pattern - albeit I'm setting my timeout to Timeout.Infinite - where as you are reducing the timeout in your test to 500ms. So we couldn't say that the test you mentioned precisely tests what I am experiencing.

However, your point is taken - it could very well be that the server I am hitting is timing out the request. I was unaware that I might get an ErrorException on the IRestResponse based on status code. I was under the, apparently false, impression that the ErrorException would only occur if some exception were thrown during the request execution process.

I'll run my request in Fiddler to verify what I am getting back from the server. Thank you for taking the time to respond to me!

**Comment by maplemale** [comment]
@alexeyzimarev I for one would LOVE to debug against my own project / code and identify the root of the issue! Already attempted to do so for several hours and ran out of time trouble-shooting build errors in the solution / projects. This issue was mentioned before and closed, albeit not very clearly (as a build error):

The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion". RestSharp 

If someone can assist me with this as I've basically given up... I can at least re-run my code which reproduces the issue fairly consistently and send you a stack trace or maybe even resolve the issue for you.

My guess is the issue may be due to missing git components in my environment. I do not / have never integrated any of my own projects with Git (We use pure TFS)

**Comment by boylec** [comment]
@alexeyzimarev Unfortunately (or fortunately?) it seems the timeout I was previously experiencing is no longer occurring at least for the time being. Perhaps the server I was hitting has fixed whatever issue they may have been having. 

The issue is somewhat intermittent.

I'm going to assume you are correct about the server timing the request out and leave it at that. The next time I see that the timeouts are occurring, if I can prove it isn't the server timing the request out - and that it is indeed the client - I'll report back with evidence.

Thanks for your patience and help.

**Comment by alexeyzimarev** [comment]
I mentioned the tests because the original issue was that the timeout is being ignored.

**Comment by icnocop** [comment]
Update to RestSharp v106.2.2.
See https://github.com/restsharp/RestSharp/issues/1093
