### ISSUE TITLE
DeserializeAs with an underscore in the name is not working properly when Deserializing

### ISSUE THREAD

**Issue by keithazzopardi** [restsharp/RestSharp#979]
RestSharp does not deserialize properly XML attributes that have an underscore in the C# class properties. In order for this to work, I had to omit the underscore from the DeserializeAs attribute.
```
<response>
     <target_id>264</target_id>
     <new_entity_id>295</new_entity_id>
<response>
```

```
public class Response
{
            [DeserializeAs(Name = "targetId")]
            public int TargetId { get; set; }

            [DeserializeAs(Name = "newentityid")]
            public string EntityId { get; set; }
}

```

**Comment by pnmcosta** [comment]
Thank you, I just came across this myself 👍

**Comment by scmason07** [comment]
Which version of RestSharp are you using to get this issue? I wrote a test using your class and XML above and was unable to replicate the issue on any recent version.

```
[Test]
public void Can_Use_DeserializeAs_With_Underscores()
{
	const string content =
		"<response><target_id>264</target_id><new_entity_id>295</new_entity_id></response>";
	XmlDeserializer xml = new XmlDeserializer();
	var output = xml.Deserialize<Response>(new RestResponse { Content = content });

	Assert.NotNull(output);
	Assert.AreEqual(264, output.TargetId);
	Assert.AreEqual("295", output.EntityId);
}
```
This passes.

The only way I was able to replicate this issue was by digging out a old release (I used 104.2). This seems to be before XmlDeserializer became the base class for XmlAttributeDeserializer. In this release, there isn't any reference to DeserializeAsAttribute in the XmlDeserializer, so the attribute would have been ignored.

I'd say this is no longer an issue.

**Comment by alexeyzimarev** [comment]
Cool, thanks for confirming.
